// GENERATED by tools/build.mjs. Do not edit.
export const API_BASE = "https://emm-blog-app.expo.app";
/** Recipe share links (the /r page on EAS Hosting). */
export const SHARE_BASE = "https://emm-blog-app.expo.app/r";
