// GENERATED by tools/build.mjs from emm-blog-app/src/features/grocery/catalog.ts. Do not edit.
// Grocery catalog engine. Pure TS (no React Native imports) so it can be tested with node.
//
//   matchItem('organic baby spinach')  -> Spinach (Produce)     fuzzy-ish: plural + synonym + sub-phrase
//   exactItem('scallions')             -> Green onions           whole-name match only (used for de-duping)
//   aisleOf('2% milk')                 -> 'dairy'
//   searchCatalog('avo', 6)            -> [Avocado, Avocado oil…] prefix + word-start + typo tolerant
//
// Everything is built once, lazily, on first use (a few ms for ~2,000 items).
import { AISLE_DEFS, RAW } from './catalogData.js';
export { AISLE_DEFS } from './catalogData.js';
// ---------------------------------------------------------------------------
// normalizing
// ---------------------------------------------------------------------------
const IRREGULAR = {
    loaves: 'loaf',
    leaves: 'leaf',
    knives: 'knife',
    halves: 'half',
    potatoes: 'potato',
    tomatoes: 'tomato',
    mangoes: 'mango',
    avocadoes: 'avocado',
    mice: 'mouse',
    geese: 'goose',
    teeth: 'tooth',
};
const KEEP = new Set(['hummus', 'asparagus', 'couscous', 'swiss', 'molasses', 'brussels', 'series', 'species', 'citrus', 'octopus', 'lotus', 'tofus']);
/** lowercase, no accents, "&" -> "and", punctuation -> spaces. */
export function norm(s) {
    return s
        .toLowerCase()
        .normalize('NFD')
        .replace(/[̀-ͯ]/g, '')
        .replace(/&/g, ' and ')
        .replace(/['’]/g, '')
        .replace(/[^a-z0-9%]+/g, ' ')
        .trim();
}
/** Very small English singularizer. Applied the same way to catalog keys and queries, so it only needs to be consistent. */
export function singular(w) {
    if (w.length < 4 || KEEP.has(w))
        return w;
    const irr = IRREGULAR[w];
    if (irr)
        return irr;
    if (w.endsWith('ies') && w.length > 4)
        return `${w.slice(0, -3)}y`;
    if (/(ches|shes|xes|sses|zzes)$/.test(w))
        return w.slice(0, -2);
    if (w.endsWith('oes'))
        return w.slice(0, -2);
    if (w.endsWith('s') && !/(ss|us|is)$/.test(w))
        return w.slice(0, -1);
    return w;
}
/** Normalized + singular key: "Cherry Tomatoes!" -> "cherry tomato". */
export function keyOf(s) {
    const n = norm(s);
    if (!n)
        return '';
    return n.split(' ').map(singular).join(' ');
}
let built = null;
function build() {
    const items = [];
    const byAisle = new Map();
    const sections = new Map();
    for (const a of AISLE_DEFS) {
        byAisle.set(a.id, []);
        sections.set(a.id, []);
    }
    const list = (s) => (s ? s.split(',').map((x) => x.trim()).filter(Boolean) : []);
    for (const [aisle, block] of Object.entries(RAW)) {
        let section = null;
        for (const rawLine of block.split('\n')) {
            const line = rawLine.trim();
            if (!line)
                continue;
            if (line.startsWith('#')) {
                section = { sub: line.replace(/^#+\s*/, ''), items: [] };
                sections.get(aisle).push(section);
                continue;
            }
            if (!section) {
                section = { sub: 'More', items: [] };
                sections.get(aisle).push(section);
            }
            const [head, unit = '', syn = '', tags = ''] = line.split('|').map((s) => s.trim());
            const sp = head.indexOf(' ');
            const emoji = head.slice(0, sp);
            const name = head.slice(sp + 1).trim();
            const it = {
                id: `${aisle}:${keyOf(name)}`,
                name,
                emoji,
                aisle,
                unit: unit || null,
                syn: list(syn),
                sub: section.sub,
                tags: list(tags),
            };
            items.push(it);
            byAisle.get(aisle).push(it);
            section.items.push(it);
        }
    }
    const byKey = new Map();
    const byId = new Map();
    // names win over synonyms: register every name first
    for (const it of items) {
        byId.set(it.id, it);
        const k = keyOf(it.name);
        if (!byKey.has(k))
            byKey.set(k, it);
    }
    for (const it of items) {
        for (const s of it.syn) {
            const k = keyOf(s);
            if (k && !byKey.has(k))
                byKey.set(k, it);
        }
    }
    const byLetter = new Map();
    const put = (e) => {
        const seen = new Set();
        for (const w of e.text.split(' ')) {
            const ch = w[0];
            if (!ch || seen.has(ch))
                continue;
            seen.add(ch);
            const arr = byLetter.get(ch);
            if (arr)
                arr.push(e);
            else
                byLetter.set(ch, [e]);
        }
    };
    for (const it of items) {
        put({ text: norm(it.name), item: it, w: 1 });
        for (const s of it.syn)
            put({ text: norm(s), item: it, w: 0.78 });
        for (const s of it.tags)
            put({ text: norm(s), item: it, w: 0.6 });
    }
    return { items, byKey, byId, byAisle, sections, byLetter };
}
const B = () => (built ?? (built = build()));
export const catalogItems = () => B().items;
export const catalogByAisle = (a) => B().byAisle.get(a) ?? [];
export const catalogById = (id) => B().byId.get(id) ?? null;
/** The aisle's subcategory sections in catalog order (empty for 'other'). */
export const catalogSections = (a) => B().sections.get(a) ?? [];
// ---------------------------------------------------------------------------
// lookups
// ---------------------------------------------------------------------------
/** Whole-name match (plural/synonym/case tolerant). */
export function exactItem(name) {
    const k = keyOf(name);
    return k ? (B().byKey.get(k) ?? null) : null;
}
const matchCache = new Map();
/**
 * Best catalog item for free text. Tries the whole name, then sub-phrases that end with the last word
 * (the head noun: "chocolate chip cookies" -> cookies), longest first, then any other sub-phrase.
 */
export function matchItem(name) {
    const k = keyOf(name);
    if (!k)
        return null;
    const hit = matchCache.get(k);
    if (hit !== undefined)
        return hit;
    const map = B().byKey;
    let found = map.get(k) ?? null;
    if (!found) {
        const w = k.split(' ');
        const n = w.length;
        // phrases ending at the last word
        for (let len = n - 1; len >= 1 && !found; len--)
            found = map.get(w.slice(n - len).join(' ')) ?? null;
        // any other phrase, longest first, rightmost first
        for (let len = n - 1; len >= 1 && !found; len--) {
            for (let s = n - len - 1; s >= 0 && !found; s--)
                found = map.get(w.slice(s, s + len).join(' ')) ?? null;
        }
    }
    if (matchCache.size > 3000)
        matchCache.clear();
    matchCache.set(k, found);
    return found;
}
export function aisleOf(name) {
    return matchItem(name)?.aisle ?? 'other';
}
const AISLE_BY_ID = new Map(AISLE_DEFS.map((a) => [a.id, a]));
export function aisleInfo(id) {
    return AISLE_BY_ID.get(id) ?? AISLE_DEFS[AISLE_DEFS.length - 1];
}
export const isAisleId = (id) => AISLE_BY_ID.has(id);
/** Emoji for any item text: catalog emoji, else the aisle's emoji. */
export function emojiOf(name, aisleOverride) {
    const it = matchItem(name);
    if (it)
        return it.emoji;
    return aisleInfo(aisleOverride ?? 'other').emoji;
}
/**
 * Identity used to spot duplicates on a list: the catalog item id when the whole name is a catalog item
 * (so "Scallions" and "green onions" are the same), else the normalized singular text.
 */
export function itemKey(name) {
    const it = exactItem(name);
    return it ? it.id : keyOf(name);
}
/** Display name for typed text: the catalog's own name when she typed it (any case/plural), else her text, capitalized. */
export function canonicalName(typed) {
    const t = typed.replace(/\s+/g, ' ').trim();
    const it = exactItem(t);
    if (it && keyOf(it.name) === keyOf(t))
        return it.name;
    return t.charAt(0).toUpperCase() + t.slice(1);
}
/** Bounded Levenshtein (returns max+1 when over). */
export function editDistance(a, b, max = 2) {
    if (Math.abs(a.length - b.length) > max)
        return max + 1;
    let prev = Array.from({ length: b.length + 1 }, (_, i) => i);
    for (let i = 1; i <= a.length; i++) {
        const cur = [i];
        let rowMin = i;
        for (let j = 1; j <= b.length; j++) {
            const v = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
            cur.push(v);
            if (v < rowMin)
                rowMin = v;
        }
        if (rowMin > max)
            return max + 1;
        prev = cur;
    }
    return prev[b.length];
}
function scoreText(q, qWords, t) {
    if (t === q)
        return 1000;
    const extra = Math.min(100, t.length - q.length);
    // whole words beat a word that merely starts the same ("milk" -> Milk tea, Oat milk before Milka)
    if (t.startsWith(`${q} `))
        return 900 - extra;
    if (` ${t} `.includes(` ${q} `))
        return 780 - extra;
    if (t.startsWith(q))
        return 760 - extra;
    if (` ${t}`.includes(` ${q}`))
        return 620 - extra;
    if (qWords.length > 1) {
        const tw = t.split(' ');
        if (qWords.every((qw) => tw.some((w) => w.startsWith(qw))))
            return 520 - Math.min(100, t.length);
    }
    return 0;
}
function fuzzyScore(q, t) {
    if (q.length < 4)
        return 0;
    const max = q.length >= 7 ? 2 : 1;
    let best = max + 1;
    // compare with the whole text, each word, and the text's prefix of the same length (typo while typing)
    best = Math.min(best, editDistance(q, t, max), editDistance(q, t.slice(0, q.length), max));
    for (const w of t.split(' ')) {
        if (w.length < 3)
            continue;
        best = Math.min(best, editDistance(q, w, max), editDistance(q, w.slice(0, q.length), max));
        if (best === 0)
            break;
    }
    return best <= max ? 300 - best * 60 : 0;
}
/**
 * Autocomplete. `boost(item)` lets callers rank her favorites first (history).
 * Prefix and word-start matches first; typo-tolerant matches fill the rest.
 */
export function searchCatalog(query, limit = 8, boost, onlyAisle) {
    const q = norm(query);
    if (!q)
        return [];
    const qWords = q.split(' ');
    const qSing = keyOf(q);
    const cands = B().byLetter.get(q[0]) ?? [];
    const best = new Map();
    const consider = (item, s) => {
        if (s <= 0 || (onlyAisle && item.aisle !== onlyAisle))
            return;
        const total = s + (boost ? boost(item) : 0);
        const cur = best.get(item.id);
        if (!cur || cur.score < total)
            best.set(item.id, { item, score: total });
    };
    for (const e of cands) {
        let s = scoreText(q, qWords, e.text);
        if (!s && qSing !== q)
            s = scoreText(qSing, qSing.split(' '), keyOf(e.text)) - 20;
        // a synonym (or generic tag) hit counts less than a hit on the item's own name
        if (s)
            consider(e.item, s * e.w);
    }
    if (best.size < limit && q.length >= 4) {
        const ex = exactItem(q);
        if (ex)
            consider(ex, 990);
        for (const e of cands) {
            if (best.has(e.item.id))
                continue;
            const f = fuzzyScore(q, e.text);
            if (e.w >= 0.78)
                consider(e.item, e.w === 1 ? f : f * 0.8);
        }
    }
    return [...best.values()].sort((a, b) => b.score - a.score || a.item.name.length - b.item.name.length).slice(0, limit);
}
/** Catalog items per aisle, for the stats line in docs/tests. */
export function catalogStats() {
    const out = {};
    for (const it of B().items)
        out[it.aisle] = (out[it.aisle] ?? 0) + 1;
    return out;
}
