// GENERATED by tools/build.mjs: loads data/catalog.json (the app's catalogData.ts) once, when grocery code is imported.
const res = await fetch(new URL('../../../data/catalog.json', import.meta.url));
if (!res.ok) throw new Error('catalog ' + res.status);
const data = await res.json();
export const AISLE_DEFS = data.aisles;
export const RAW = data.raw;
