// GENERATED by tools/build.mjs from emm-blog-app/src/features/grocery/historyModel.ts. Do not edit.
// What she buys, learned over time. Pure TS: the kv-backed store lives in history.ts.
//
// key = itemKey(name) (catalog id or normalized name). Each entry counts adds (typed/tapped) and purchases
// ("Done shopping"), remembers the last price/qty, and keeps a smoothed interval between purchases so we can
// guess when she's "running low".
const DAY = 86400000;
const blank = (name) => ({ name, n: 0, a: 0, last: 0, iv: null, price: null, qty: null });
export function recordAdd(h, key, name) {
    const cur = h[key] ?? blank(name);
    return { ...h, [key]: { ...cur, name, a: cur.a + 1 } };
}
export function recordPurchase(h, key, name, now, price, qty) {
    const cur = h[key] ?? blank(name);
    let iv = cur.iv;
    if (cur.last) {
        const days = (now - cur.last) / DAY;
        // same-day repeats don't teach us anything about the rhythm
        if (days >= 1)
            iv = iv === null ? days : iv * 0.6 + days * 0.4;
    }
    return { ...h, [key]: { ...cur, name, n: cur.n + 1, last: now, iv, price: price ?? cur.price, qty: qty ?? cur.qty } };
}
/** Ranking boost for autocomplete (0 for strangers). */
export function boostOf(e) {
    if (!e)
        return 0;
    return Math.round(Math.log2(1 + e.n * 2 + e.a) * 70);
}
/** Her most-bought/added things that aren't on the list yet. */
export function usuals(h, onList, limit = 12) {
    return Object.entries(h)
        .filter(([k, e]) => !onList.has(k) && e.n * 3 + e.a >= 3)
        .sort((x, y) => y[1].n * 3 + y[1].a - (x[1].n * 3 + x[1].a) || y[1].last - x[1].last)
        .slice(0, limit)
        .map(([key, entry]) => ({ key, name: entry.name, entry }));
}
/** Things she buys on a rhythm and is probably out of by now. */
export function runningLow(h, onList, now, limit = 8) {
    const out = [];
    for (const [key, e] of Object.entries(h)) {
        if (onList.has(key) || e.n < 2 || !e.iv || !e.last)
            continue;
        const ratio = (now - e.last) / DAY / Math.max(1, e.iv);
        if (ratio >= 0.85)
            out.push({ s: { key, name: e.name, entry: e }, ratio });
    }
    return out
        .sort((a, b) => b.ratio - a.ratio)
        .slice(0, limit)
        .map((x) => x.s);
}
/** Names from history that match a typed prefix (for things that aren't in the catalog). */
export function historyMatches(h, qNorm, limit = 3) {
    if (!qNorm)
        return [];
    const out = [];
    for (const [key, e] of Object.entries(h)) {
        const n = e.name.toLowerCase();
        if (n.startsWith(qNorm) || n.includes(` ${qNorm}`))
            out.push({ key, name: e.name, entry: e });
    }
    return out.sort((a, b) => boostOf(b.entry) - boostOf(a.entry)).slice(0, limit);
}
