// GENERATED by tools/build.mjs from emm-blog-app/src/features/grocery/money.ts. Do not edit.
// Estimated total for a shopping list: price × leading qty ("3" avocados at $1.20 = $3.60, "2 lb" at $4 = $8).
import { parseItemText } from '../lists/model.js';
import { currencyOf, parsePrice, qtyCount } from './parse.js';
export function estimate(items) {
    let total = 0;
    let openTotal = 0;
    let priced = 0;
    let unpriced = 0;
    let symbol = null;
    for (const i of items) {
        const m = parseItemText(i.text);
        const p = parsePrice(m.price);
        if (p === null) {
            unpriced++;
            continue;
        }
        symbol ?? (symbol = currencyOf(m.price));
        const line = p * qtyCount(i.qty);
        total += line;
        if (!i.checked)
            openTotal += line;
        priced++;
    }
    return { total, openTotal, priced, unpriced, symbol: symbol ?? '$' };
}
