// GENERATED by tools/build.mjs from emm-blog-app/src/features/grocery/order.ts. Do not edit.
// Store order (which aisle comes first when she walks the store) + grouping + her WinCo aisle numbers. Pure TS.
import { AISLE_DEFS, aisleInfo, catalogByAisle, isAisleId } from './catalog.js';
/**
 * Default walk = a WinCo Foods, from the entrance around the store (see ARCHITECTURE.md "WinCo order").
 * Based on WinCo's published store map (#52 Brentwood): produce along the entrance wall, bulk bins in the corner,
 * deli / seafood / meat along the back wall, the "A" grocery aisles (cereal & coffee → baking & spices → pasta & rice →
 * Asian/Mexican → canned & condiments → health & beauty → cards → cookies/candy → chips), then across the front to the
 * bakery + soft drinks and up the "B" side (paper, housewares, hardware, baby, pet, cleaning), frozen, and dairy last.
 * Stores vary, so she can reorder + label aisle numbers.
 */
export const WINCO_ORDER = [
    'produce',
    'bulk',
    'deli',
    'meat',
    'breakfast',
    'baking',
    'spices',
    'grains',
    'international',
    'canned',
    'condiments',
    'personal',
    'pharmacy',
    'party',
    'snacks',
    'bakery',
    'drinks',
    'paper',
    'housewares',
    'hardware',
    'baby',
    'pet',
    'household',
    'frozen',
    'plant',
    'dairy',
    'other',
];
export const DEFAULT_ORDER = [...WINCO_ORDER, ...AISLE_DEFS.map((a) => a.id).filter((id) => !WINCO_ORDER.includes(id))];
/** The order the app used before WinCo became the default. A saved order equal to it was never customized. */
export const LEGACY_ORDER = [
    'produce', 'bakery', 'deli', 'meat', 'dairy', 'plant', 'breakfast', 'grains', 'canned', 'condiments', 'spices', 'baking',
    'international', 'snacks', 'drinks', 'frozen', 'baby', 'pet', 'household', 'paper', 'personal', 'pharmacy', 'party', 'other',
];
/**
 * Saved order (maybe partial, maybe with stale ids) -> every aisle exactly once.
 * Nothing saved (or the untouched old default) -> the WinCo order. Aisles missing from a saved order (new ones like
 * Bulk / Home & hardware) slot in right after the aisle that precedes them in the WinCo order.
 */
export function orderAisles(saved) {
    const out = [];
    const seen = new Set();
    for (const id of saved ?? []) {
        if (isAisleId(id) && !seen.has(id)) {
            seen.add(id);
            out.push(id);
        }
    }
    if (!out.length || sameOrder(out, LEGACY_ORDER))
        return [...DEFAULT_ORDER];
    DEFAULT_ORDER.forEach((id, i) => {
        if (seen.has(id))
            return;
        seen.add(id);
        // after the nearest WinCo predecessor she has placed; at the top when none
        let at = 0;
        for (let j = i - 1; j >= 0; j--) {
            const k = out.indexOf(DEFAULT_ORDER[j]);
            if (k >= 0) {
                at = k + 1;
                break;
            }
        }
        out.splice(at, 0, id);
    });
    return out;
}
const sameOrder = (a, b) => a.length === b.length && a.every((x, i) => x === b[i]);
/** Aisles worth showing in pickers/walks: ones with catalog items, plus 'other' (unless `withOther` is false) and any in `keep` (e.g. aisles her list uses). */
export function visibleAisles(order, keep, withOther = true) {
    return order.filter((a) => (a === 'other' ? withOther : catalogByAisle(a).length > 0) || !!keep?.has(a));
}
/**
 * Reorder the visible aisles, then put the hidden ones back where they were relative to the full order
 * (so ↑/↓ never "swaps" with an invisible empty aisle).
 */
export function withVisibleOrder(full, visible) {
    const vis = new Set(visible);
    let v = 0;
    return full.map((a) => (vis.has(a) ? visible[v++] : a));
}
/** Clean what she typed: "7" / "aisle 7" / " 7a " -> "7" / "7" / "7A"; free text ("Back wall") is kept (max 14 chars). */
export function cleanAisleNumber(raw) {
    let t = (raw ?? '').replace(/\s+/g, ' ').trim();
    t = t.replace(/^aisle\s*#?\s*/i, '').replace(/^#\s*/, '');
    if (/^\d+[a-z]?$/i.test(t))
        t = t.toUpperCase();
    return t.slice(0, 14);
}
/** "7" -> "Aisle 7", "Back wall" -> "Back wall", "" -> "". */
export function aisleNumberLabel(num) {
    const t = cleanAisleNumber(num);
    if (!t)
        return '';
    return /^\d/.test(t) ? `Aisle ${t}` : t;
}
/** "Aisle 7 · Breakfast & cereal" (or just the label when she hasn't numbered it). */
export function aisleTitle(aisle, nums) {
    const label = aisleInfo(aisle).label;
    const n = aisleNumberLabel(nums?.[aisle]);
    return n ? `${n} · ${label}` : label;
}
/** Aisle line in shared text: "🥣 AISLE 7 · BREAKFAST & CEREAL". */
export function aisleShareHeading(aisle, nums) {
    return `${aisleInfo(aisle).emoji} ${aisleTitle(aisle, nums).toUpperCase()}`;
}
/** Move one aisle up (-1) or down (+1). Returns a new array (same one if it can't move). */
export function moveAisle(order, id, dir) {
    const i = order.indexOf(id);
    const j = i + dir;
    if (i < 0 || j < 0 || j >= order.length)
        return order;
    const next = [...order];
    [next[i], next[j]] = [next[j], next[i]];
    return next;
}
/** Move an aisle to an exact position (drag). */
export function placeAisle(order, id, to) {
    const from = order.indexOf(id);
    if (from < 0)
        return order;
    const next = order.filter((x) => x !== id);
    next.splice(Math.max(0, Math.min(next.length, to)), 0, id);
    return next;
}
/** Group items by aisle in store order, skipping empty aisles. Items keep their relative order. */
export function groupByAisle(items, aisleFn, order) {
    const buckets = new Map();
    for (const it of items) {
        let a = aisleFn(it);
        if (!isAisleId(a))
            a = 'other';
        const arr = buckets.get(a);
        if (arr)
            arr.push(it);
        else
            buckets.set(a, [it]);
    }
    const out = [];
    for (const a of order) {
        const arr = buckets.get(a);
        if (arr?.length)
            out.push({ aisle: a, items: arr });
    }
    return out;
}
