// GENERATED by tools/build.mjs from emm-blog-app/src/features/grocery/parse.ts. Do not edit.
// Parsing typed grocery text + quantity math. Pure TS (node-testable).
//
//   parseGroceryInput('2 lb chicken')        -> { name: 'Chicken', qty: '2 lb' }
//   parseGroceryInput('milk x2')             -> { name: 'Milk', qty: '2' }
//   parseGroceryInput('a dozen eggs')        -> { name: 'Eggs', qty: '1 dozen' }
//   parseGroceryInput('3 avocados')          -> { name: 'Avocado', qty: '3' }
//   parseGroceryInput('oat milk (barista) $4.50') -> { name: 'Oat milk', note: 'barista', price: '$4.50' }
//   splitMulti('milk, eggs, bread')          -> ['milk', 'eggs', 'bread']
//   mergeQty('2', null, 'bump') -> '3'   mergeQty('1 lb', '2 lbs') -> '3 lb'
import { ingredientToItem } from '../recipes/quantity.js';
import { canonicalName, exactItem, keyOf, matchItem } from './catalog.js';
// ---------------------------------------------------------------------------
// units
// ---------------------------------------------------------------------------
/** alias -> canonical unit */
const UNIT_ALIASES = {};
const UNITS = [
    ['lb', ['lb', 'lbs', 'pound', 'pounds', '#']],
    ['oz', ['oz', 'ounce', 'ounces']],
    ['fl oz', ['fl oz', 'floz']],
    ['kg', ['kg', 'kgs', 'kilo', 'kilos', 'kilogram', 'kilograms']],
    ['g', ['g', 'gr', 'gram', 'grams']],
    ['L', ['l', 'liter', 'liters', 'litre', 'litres']],
    ['ml', ['ml', 'milliliter', 'milliliters', 'millilitre', 'millilitres']],
    ['gallon', ['gallon', 'gallons', 'gal']],
    ['quart', ['quart', 'quarts', 'qt']],
    ['pint', ['pint', 'pints', 'pt']],
    ['dozen', ['dozen', 'doz']],
    ['pack', ['pack', 'packs', 'pk', 'package', 'packages', 'packet', 'packets', 'pkg']],
    ['bag', ['bag', 'bags']],
    ['box', ['box', 'boxes']],
    ['can', ['can', 'cans', 'tin', 'tins']],
    ['jar', ['jar', 'jars']],
    ['bottle', ['bottle', 'bottles']],
    ['bunch', ['bunch', 'bunches']],
    ['head', ['head', 'heads']],
    ['loaf', ['loaf', 'loaves']],
    ['carton', ['carton', 'cartons']],
    ['tub', ['tub', 'tubs', 'container', 'containers']],
    ['roll', ['roll', 'rolls']],
    ['bar', ['bar', 'bars']],
    ['stick', ['stick', 'sticks']],
    ['case', ['case', 'cases']],
    ['block', ['block', 'blocks']],
    ['tube', ['tube', 'tubes']],
    ['ct', ['ct', 'count', 'pc', 'pcs', 'piece', 'pieces']],
    ['cup', ['cup', 'cups', 'c']],
    ['tbsp', ['tbsp', 'tbs', 'tbl', 'tablespoon', 'tablespoons', 'T']],
    ['tsp', ['tsp', 'teaspoon', 'teaspoons', 't']],
    ['clove', ['clove', 'cloves']],
    ['slice', ['slice', 'slices']],
    ['sprig', ['sprig', 'sprigs']],
    ['pinch', ['pinch', 'pinches']],
    ['dash', ['dash', 'dashes']],
    ['handful', ['handful', 'handfuls']],
    ['sheet', ['sheet', 'sheets']],
    ['pouch', ['pouch', 'pouches']],
    ['tray', ['tray', 'trays']],
    ['clamshell', ['clamshell', 'clamshells']],
    ['canister', ['canister', 'canisters']],
];
for (const [canon, aliases] of UNITS)
    for (const a of aliases)
        UNIT_ALIASES[a.toLowerCase()] = canon;
const PLURAL = {
    box: 'boxes',
    bunch: 'bunches',
    loaf: 'loaves',
    pouch: 'pouches',
    dash: 'dashes',
    pinch: 'pinches',
};
/** Units that never take an "s". */
const INVARIANT = new Set(['lb', 'oz', 'fl oz', 'kg', 'g', 'L', 'ml', 'dozen', 'ct', 'tbsp', 'tsp']);
/** Recipe measures: you don't buy "2 cups" of flour, you buy a bag. */
const COOKING = new Set(['cup', 'tbsp', 'tsp', 'g', 'ml', 'oz', 'fl oz', 'clove', 'slice', 'sprig', 'pinch', 'dash', 'handful', 'sheet', 'stick', 'ct', 'L']);
export function canonUnit(u) {
    const t = u.trim().replace(/\.$/, '');
    if (!t)
        return null;
    // 'T' (tbsp) vs 't' (tsp) is case sensitive; everything else isn't
    if (t === 'T')
        return 'tbsp';
    if (t === 't')
        return 'tsp';
    return UNIT_ALIASES[t.toLowerCase()] ?? null;
}
export function unitLabel(unit, n) {
    if (n <= 1 || INVARIANT.has(unit))
        return unit;
    return PLURAL[unit] ?? `${unit}s`;
}
export const isCookingUnit = (u) => !!u && COOKING.has(u);
// ---------------------------------------------------------------------------
// numbers
// ---------------------------------------------------------------------------
const VULGAR = { '½': 0.5, '⅓': 1 / 3, '⅔': 2 / 3, '¼': 0.25, '¾': 0.75, '⅛': 0.125 };
const WORD_NUM = {
    a: 1, an: 1, one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9, ten: 10, eleven: 11, twelve: 12,
    couple: 2, 'a couple': 2, 'a couple of': 2, 'a few': 3, few: 3, some: 1, half: 0.5, 'half a': 0.5, 'a half': 0.5,
};
const NUM_SRC = '(?:\\d+\\s+\\d+\\/\\d+|\\d+\\/\\d+|\\d*\\s?[½⅓⅔¼¾⅛]|\\d+(?:[.,]\\d+)?)';
export function parseNum(s) {
    const t = s.trim();
    let m = /^(\d+)\s+(\d+)\/(\d+)$/.exec(t);
    if (m)
        return +m[1] + +m[2] / (+m[3] || 1);
    m = /^(\d+)\/(\d+)$/.exec(t);
    if (m)
        return +m[1] / (+m[2] || 1);
    m = /^(\d*)\s?([½⅓⅔¼¾⅛])$/.exec(t);
    if (m)
        return (m[1] ? +m[1] : 0) + VULGAR[m[2]];
    m = /^(\d+)(?:[.,](\d+))?$/.exec(t);
    if (m)
        return parseFloat(`${m[1]}.${m[2] ?? '0'}`);
    const w = WORD_NUM[t.toLowerCase()];
    return w ?? null;
}
const FRACS = [[0.125, '1/8'], [0.25, '1/4'], [1 / 3, '1/3'], [0.5, '1/2'], [2 / 3, '2/3'], [0.75, '3/4']];
export function formatNum(n) {
    const whole = Math.floor(n + 1e-9);
    const frac = n - whole;
    if (frac < 0.02)
        return String(whole);
    if (frac > 0.98)
        return String(whole + 1);
    const hit = FRACS.find(([v]) => Math.abs(v - frac) < 0.02);
    if (hit)
        return whole ? `${whole} ${hit[1]}` : hit[1];
    return String(Math.round(n * 100) / 100);
}
/** "2" / "1 1/2 cups" / "3 lbs" / "½ dozen" -> {n, unit}; null when there's no leading number. */
export function parseQty(q) {
    if (!q)
        return null;
    const m = new RegExp(`^(${NUM_SRC})\\s*(.*)$`).exec(q.trim());
    if (!m)
        return null;
    const n = parseNum(m[1]);
    if (n === null)
        return null;
    const rest = m[2].trim();
    if (!rest)
        return { n, unit: null };
    return { n, unit: canonUnit(rest) ?? rest.toLowerCase() };
}
export function formatQty(q) {
    if (!q.unit)
        return q.n === 1 ? null : formatNum(q.n);
    return `${formatNum(q.n)} ${unitLabel(q.unit, q.n)}`;
}
/** Stepper +/-: "1 bag" + 1 -> "2 bags", "2" - 1 -> null (just one), "some" stays. */
export function stepQty(q, d) {
    const p = q ? parseQty(q) : { n: 1, unit: null };
    if (!p)
        return q;
    const n = Math.round((p.n + d) * 100) / 100;
    if (n <= 0)
        return null;
    return formatQty({ n, unit: p.unit });
}
/** Leading count for price math: "3" -> 3, "2 lb" -> 2, null -> 1. */
export function qtyCount(q) {
    const p = parseQty(q);
    return p && p.n > 0 ? p.n : 1;
}
/**
 * Merge two quantities of the same item.
 * - mode 'bump' (typing/tapping it again): no qty on the new one means "one more".
 * - mode 'sum' (recipes): no qty means "some", so it doesn't change anything.
 * Same units add up; different units are kept side by side ("2 lb + 1 pack").
 */
export function mergeQty(a, b, mode = 'bump') {
    if (mode === 'sum') {
        if (!a)
            return b;
        if (!b)
            return a;
    }
    const pa = a ? parseQty(a) : { n: 1, unit: null };
    const pb = b ? parseQty(b) : { n: 1, unit: null };
    if (pa && pb) {
        if (pa.unit === pb.unit)
            return formatQty({ n: pa.n + pb.n, unit: pa.unit });
        if (!b)
            return formatQty({ n: pa.n + 1, unit: pa.unit }); // "2 bags" + again -> "3 bags"
        if (!a)
            return b; // "milk" + "1 gallon milk" -> the specific one wins
    }
    if (a && b && a.trim().toLowerCase() === b.trim().toLowerCase())
        return a;
    return [a ?? '1', b ?? '1'].join(' + ');
}
// ---------------------------------------------------------------------------
// prices
// ---------------------------------------------------------------------------
const PRICE_ANY = /(?:^|\s)@?\s*([$€£¥]\s?\d+(?:[.,]\d{1,2})?|\d+(?:[.,]\d{1,2})?\s?(?:€|\$|£))(?=\s|$)/;
/** "$3.49" / "3,49 €" / "4" -> 3.49 / 3.49 / 4. */
export function parsePrice(s) {
    if (!s)
        return null;
    const m = /(\d+(?:[.,]\d{1,2})?)/.exec(s);
    if (!m)
        return null;
    const n = parseFloat(m[1].replace(',', '.'));
    return Number.isFinite(n) ? n : null;
}
export function currencyOf(s) {
    const m = s ? /[$€£¥]/.exec(s) : null;
    return m ? m[0] : null;
}
export function formatMoney(n, symbol = '$') {
    const v = Math.round(n * 100) / 100;
    const txt = v % 1 === 0 ? String(v) : v.toFixed(2);
    return symbol === '€' ? `${txt} €` : `${symbol}${txt}`;
}
/** Normalizes what she typed in a price field: "3.5" -> "$3.50", "4 €" stays. Empty -> null. */
export function cleanPrice(s, fallbackSymbol = '$') {
    const n = parsePrice(s);
    if (n === null)
        return null;
    const sym = currencyOf(s) ?? fallbackSymbol;
    return sym === '€' ? `${n.toFixed(2)} €` : `${sym}${n.toFixed(2)}`;
}
const UNIT_WORDS = Object.keys(UNIT_ALIASES)
    .filter((u) => (u.length > 1 || u === 'g' || u === 'l') && u !== '#')
    .sort((x, y) => y.length - x.length)
    .map((u) => u.replace(' ', '\\s'))
    .join('|');
const LEAD_NUM = new RegExp(`^(${NUM_SRC})\\s*(?:x|×)?\\s*(?:(${UNIT_WORDS})\\.?\\s+)?(?:of\\s+)?(.+)$`, 'i');
const LEAD_WORD = new RegExp(`^(a couple of|a couple|couple of|a few|half a|a half|half|a|an|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)\\s+(?:(${UNIT_WORDS})\\s+)?(?:of\\s+)?(.+)$`, 'i');
const TAIL_X = /^(.+?)\s*(?:x|×|\*)\s*(\d+(?:[.,]\d+)?)$/i;
const LEAD_X = /^(?:x|×)\s*(\d+)\s+(.+)$/i;
const TAIL_UNIT = new RegExp(`^(.+?)\\s+(${NUM_SRC})\\s*(${UNIT_WORDS})\\.?$`, 'i');
function qtyFrom(n, unitWord) {
    const unit = unitWord ? canonUnit(unitWord) : null;
    return formatQty({ n, unit }) ?? (unit ? `1 ${unit}` : null);
}
/** "2 lb chicken", "milk x2", "a dozen eggs", "eggs (free range)", "oat milk - barista $4". */
export function parseGroceryInput(raw) {
    let t = raw.replace(/\s+/g, ' ').trim();
    t = t.replace(/^(?:[-•*·]|\[\s?[xX ]?\]|☐|☑|✓|✔)\s*/, '');
    let price = null;
    const pm = PRICE_ANY.exec(t);
    if (pm) {
        price = pm[1].replace(/\s/g, '');
        t = (t.slice(0, pm.index) + t.slice(pm.index + pm[0].length)).trim();
    }
    let note = null;
    const paren = /\s*\(([^)]*)\)\s*$/.exec(t);
    if (paren) {
        note = paren[1].trim() || null;
        t = t.slice(0, paren.index).trim();
    }
    else {
        const dash = /\s+[-–—]\s+(.+)$/.exec(t);
        if (dash) {
            note = dash[1].trim();
            t = t.slice(0, dash.index).trim();
        }
    }
    let qty = null;
    let name = t;
    let m;
    if ((m = /^(?:a\s+|one\s+)?(half\s+(?:a\s+)?)?dozen\s+(?:of\s+)?(.+)$/i.exec(t))) {
        qty = m[1] ? '1/2 dozen' : '1 dozen';
        name = m[2];
    }
    else if ((m = LEAD_X.exec(t))) {
        qty = qtyFrom(parseNum(m[1]) ?? 1);
        name = m[2];
    }
    else if ((m = LEAD_NUM.exec(t)) && !/^\d+%/.test(t) && !/^\d+\s*(?:up|in\s*1)\b/i.test(t)) {
        const n = parseNum(m[1]);
        if (n !== null && n > 0) {
            qty = qtyFrom(n, m[2]);
            name = m[3];
        }
    }
    else if ((m = LEAD_WORD.exec(t))) {
        const n = parseNum(m[1]);
        // "a banana" -> no qty; "a bag of chips" -> 1 bag; "two avocados" -> 2
        if (n !== null && (m[2] || n !== 1))
            qty = qtyFrom(n, m[2]);
        if (n !== null)
            name = m[3];
    }
    else if ((m = TAIL_X.exec(t))) {
        qty = qtyFrom(parseNum(m[2]) ?? 1);
        name = m[1];
    }
    else if ((m = TAIL_UNIT.exec(t))) {
        const n = parseNum(m[2]);
        if (n !== null) {
            qty = qtyFrom(n, m[3]);
            name = m[1];
        }
    }
    name = name.replace(/^(?:of)\s+/i, '').replace(/[.,;:]+$/, '').trim();
    if (!name)
        name = t;
    return { name: canonicalName(name), qty, note, price };
}
/**
 * Split pasted/typed text into several items: new lines, ";" or commas ("milk, eggs, bread").
 * Commas inside numbers ("1,5 kg") and parentheses are kept.
 */
export function splitMulti(raw) {
    const out = [];
    let depth = 0;
    let cur = '';
    for (let i = 0; i < raw.length; i++) {
        const ch = raw[i];
        if (ch === '(')
            depth++;
        if (ch === ')')
            depth = Math.max(0, depth - 1);
        const isComma = ch === ',' && !(/\d/.test(raw[i - 1] ?? '') && /\d/.test(raw[i + 1] ?? ''));
        if (depth === 0 && (ch === '\n' || ch === ';' || isComma)) {
            out.push(cur);
            cur = '';
        }
        else
            cur += ch;
    }
    out.push(cur);
    return out.map((s) => s.trim()).filter(Boolean);
}
const PREP_WORDS = /\b(fresh(?:ly)?|large|small|medium|big|chopped|diced|minced|sliced|grated|shredded|crushed|ground(?= (?:black )?pepper)|finely|roughly|thinly|coarsely|ripe|boneless|skinless|cold|warm|hot|room temperature|softened|melted|packed|heaping|heaped|level|beaten|lightly|peeled|seeded|deseeded|cubed|halved|quartered|rinsed|drained|trimmed|toasted|optional|divided|organic|about|approx(?:imately)?|good quality|good-quality|extra)\b/gi;
const TAIL_JUNK = /\b(to taste|for (?:garnish|serving|frying|greasing|dusting|topping)|as needed|or more|plus more.*|if needed|at room temperature)\b.*$/i;
const SKIP = new Set(['water', 'ice water', 'boiling water', 'warm water', 'cold water', 'hot water', 'tap water']);
const PURCHASE_UNITS = new Set(['lb', 'kg', 'can', 'jar', 'bunch', 'head', 'pack', 'bag', 'bottle', 'box', 'dozen', 'loaf', 'carton', 'tub', 'block', 'gallon', 'quart', 'pint', 'bar', 'roll', 'tube', 'pouch']);
/**
 * "2 cups flour, sifted" -> { name: 'Flour', qty: null, need: '2 cups' }
 * "3 large eggs"         -> { name: 'Eggs', qty: '3', need: null }
 * "1 lb ground beef"     -> { name: 'Ground beef', qty: '1 lb', need: null }
 * "Water"                -> null (skipped)
 */
export function ingredientToGrocery(line) {
    // "1 (14 oz) can tomatoes" -> "1 can tomatoes"
    // "~2 tbsp oil" (an AI-estimated amount) reads like "2 tbsp oil"
    const base = ingredientToItem(line.replace(/^\s*[~≈]\s*/, '').replace(/\s*\([^)]*\)\s*/g, ' ').trim());
    let clean = base.text.replace(TAIL_JUNK, '').replace(PREP_WORDS, ' ').replace(/\s+/g, ' ').replace(/^(?:of|and)\s+/i, '').trim();
    if (!clean)
        clean = base.text;
    if (SKIP.has(keyOf(clean)) || SKIP.has(clean.toLowerCase()))
        return null;
    // exact first (so "diced tomatoes" stays canned), then the cleaned-up name
    const hit = exactItem(base.text) ?? matchItem(clean);
    const name = hit ? hit.name : canonicalName(clean);
    const q = parseQty(base.qty);
    if (!q)
        return { name, qty: null, need: null };
    if (!q.unit) {
        const n = Math.ceil(q.n - 1e-9);
        return { name, qty: n > 1 ? String(n) : null, need: null };
    }
    if (PURCHASE_UNITS.has(q.unit))
        return { name, qty: formatQty(q), need: null };
    return { name, qty: null, need: formatQty(q) ?? base.qty };
}
