// GENERATED by tools/build.mjs from emm-blog-app/src/features/grocery/walkModel.ts. Do not edit.
// Aisle walk ("grocery list builder") draft model. Pure TS (no React Native imports) so node can test it.
//
// A draft is what she picked while walking the store aisle by aisle:
//   picks: { [key]: { name, emoji, aisle, n, unit, note } }
// key = the catalog item id ("dairy:milk") or, for her own things, itemKey(name) (catalog id when it's a catalog name).
// Turning a draft into list rows goes through draftToIncoming() (store order, qty strings like "2 lb").
import { aisleOf, canonicalName, catalogById, emojiOf, itemKey } from './catalog.js';
import { groupByAisle } from './order.js';
import { formatQty, parseQty } from './parse.js';
export const emptyDraft = (target, aisle) => ({ v: 1, target, aisle, picks: {}, prefill: {}, updatedAt: Date.now() });
/** A fresh pick for a catalog item: one of its default unit. */
export function pickFromItem(it, t = Date.now()) {
    return { key: it.id, name: it.name, emoji: it.emoji, aisle: it.aisle, n: 1, unit: it.unit, note: null, t };
}
/** Her own thing ("the good sourdough"), filed under the aisle she typed it in. */
export function pickFromText(text, aisle, t = Date.now()) {
    const name = canonicalName(text);
    const key = itemKey(name);
    const it = catalogById(key);
    return { key, name, emoji: it?.emoji ?? emojiOf(name, aisle), aisle, n: 1, unit: it?.unit ?? null, note: null, t };
}
/** A list row -> pick (qty "2 lb" -> n 2, unit lb; "some" -> 1 each, qty kept as a note-free label). */
export function pickFromRow(name, qty, note, aisle, t) {
    const key = itemKey(name);
    const it = catalogById(key);
    const q = parseQty(qty);
    const clean = q && formatQty(q) === qty;
    return {
        key,
        name,
        emoji: it?.emoji ?? emojiOf(name, aisle),
        aisle,
        n: q ? q.n : 1,
        unit: q ? q.unit : null,
        note,
        t,
        raw: qty && !clean ? qty : null,
    };
}
/** "2 lb", "1 dozen", "3", or null for just one (each). */
export const pickQty = (p) => p.raw || formatQty({ n: p.n, unit: p.unit });
/** Stepper label: "1 lb", "2 bags", "×3", "1". */
export function pickLabel(p) {
    if (p.raw)
        return p.raw;
    if (!p.unit)
        return p.n === 1 ? '1' : `×${formatQty({ n: p.n, unit: null })}`;
    return formatQty({ n: p.n, unit: p.unit }) ?? `1 ${p.unit}`;
}
/** Whole steps; lb/kg go down to 1/2 before deselecting ("1/2 lb" of deli turkey). 0 = deselect. */
export function stepN(n, d, unit) {
    const half = unit === 'lb' || unit === 'kg';
    if (half && (n < 1 || (n === 1 && d < 0)))
        return Math.max(0, Math.round((n + d * 0.5) * 100) / 100);
    return Math.max(0, Math.round((n + d) * 100) / 100);
}
/**
 * Draft -> rows for the list, in store order (aisle by aisle, in the order she picked them).
 * `aisle` is only set when she filed something somewhere the catalog wouldn't (her manual override).
 */
export function draftToIncoming(picks, order) {
    const all = Object.values(picks)
        .filter((p) => p.n > 0 && p.name.trim())
        .sort((a, b) => a.t - b.t);
    const out = [];
    for (const g of groupByAisle(all, (p) => p.aisle, order)) {
        for (const p of g.items) {
            out.push({ key: p.key, name: p.name, qty: pickQty(p), note: p.note?.trim() || null, aisle: aisleOf(p.name) === p.aisle ? null : p.aisle });
        }
    }
    return out;
}
/** For "Add by aisle" on an existing list: what to write so the list matches her picks. */
export function planSave(picks, prefill, order) {
    const plan = { add: [], update: [], remove: [] };
    for (const inc of draftToIncoming(picks, order)) {
        const pre = prefill[inc.key];
        if (!pre) {
            plan.add.push(inc);
            continue;
        }
        if ((pre.qty ?? null) !== inc.qty || (pre.note ?? null) !== inc.note)
            plan.update.push({ itemId: pre.itemId, qty: inc.qty, note: inc.note });
    }
    for (const [key, pre] of Object.entries(prefill))
        if (!picks[key] || picks[key].n <= 0)
            plan.remove.push(pre.itemId);
    return plan;
}
/** Count of picks per aisle (chip badges). */
export function countByAisle(picks) {
    const m = new Map();
    for (const p of Object.values(picks))
        m.set(p.aisle, (m.get(p.aisle) ?? 0) + 1);
    return m;
}
/** "Groceries · Sep 25" */
export function defaultListName(d = new Date()) {
    const m = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][d.getMonth()];
    return `Groceries · ${m} ${d.getDate()}`;
}
