// GENERATED by tools/build.mjs from emm-blog-app/src/features/recipes/clipTypes.ts. Do not edit.
// Shared contract for POST /api/recipe-clips (used by the API route AND the app) + the pure clip validation.
// Pure TS only: no React Native or server imports (the self-test and node tests run it as-is).
export const CLIP_MIN = 5;
export const CLIP_MAX = 60;
export const CLIPS_MAX_STEPS = 60;
export const CLIPS_MAX_STEP_CHARS = 600;
/** A YouTube video id from any watch / youtu.be / shorts / embed link (null otherwise). Mirrors server/sources.ts. */
export function youtubeIdOf(raw) {
    if (!raw)
        return null;
    let u;
    try {
        u = new URL(raw.trim());
    }
    catch {
        return null;
    }
    if (u.protocol !== 'https:' && u.protocol !== 'http:')
        return null;
    const host = u.hostname.replace(/^(www|m|music)\./, '');
    if (host === 'youtu.be')
        return /^\/([\w-]{11})(?:$|[/?#])/.exec(u.pathname + '/')?.[1] ?? null;
    if (host !== 'youtube.com' && host !== 'youtube-nocookie.com')
        return null;
    const v = u.searchParams.get('v');
    if (v && /^[\w-]{11}$/.test(v))
        return v;
    return /^\/(?:shorts|embed|live|v)\/([\w-]{11})/.exec(u.pathname)?.[1] ?? null;
}
export const isVideoId = (s) => typeof s === 'string' && /^[\w-]{11}$/.test(s);
/**
 * Clamp one clip: whole seconds, inside [0, duration], 5–60 s long. Returns null for junk
 * (non-numbers, negative, start past the end of the video).
 */
export function normalizeClip(raw, duration) {
    if (!raw || typeof raw !== 'object')
        return null;
    const r = raw;
    if (typeof r.start !== 'number' || !Number.isFinite(r.start))
        return null;
    const dur = typeof duration === 'number' && duration > 0 && Number.isFinite(duration) ? Math.floor(duration) : null;
    let start = Math.max(0, Math.floor(r.start));
    let end = typeof r.end === 'number' && Number.isFinite(r.end) ? Math.ceil(r.end) : start + 20;
    if (dur !== null && start >= dur)
        return null;
    if (start > 24 * 3600)
        return null;
    if (end - start < CLIP_MIN)
        end = start + CLIP_MIN;
    if (end - start > CLIP_MAX)
        end = start + CLIP_MAX;
    if (dur !== null && end > dur) {
        end = dur;
        if (end - start < CLIP_MIN)
            start = Math.max(0, end - CLIP_MIN);
    }
    if (end <= start)
        return null;
    return { start, end };
}
/**
 * The whole list: one entry per step (padded / cut to `stepCount`), each clamped, and "monotonic-ish":
 * steps may overlap or step back a little (a recap, a quick look back), but a clip that jumps back more than
 * 90 s before the previous clip is almost always a mistake (the intro/teaser), so it's dropped.
 */
export function sanitizeClips(raw, stepCount, duration) {
    const arr = Array.isArray(raw) ? raw : [];
    const out = [];
    let prevStart = -1;
    for (let i = 0; i < Math.min(stepCount, CLIPS_MAX_STEPS); i++) {
        const c = normalizeClip(arr[i], duration);
        if (c && prevStart >= 0 && c.start < prevStart - 90) {
            out.push(null);
            continue;
        }
        if (c)
            prevStart = c.start;
        out.push(c);
    }
    return out;
}
/** "0:42", "12:05", "1:02:03" */
export function formatClipTime(sec) {
    const s = Math.max(0, Math.floor(sec));
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    const ss = String(s % 60).padStart(2, '0');
    return h ? `${h}:${String(m).padStart(2, '0')}:${ss}` : `${m}:${ss}`;
}
