// GENERATED by tools/build.mjs from emm-blog-app/src/features/recipes/editDiff.ts. Do not edit.
// Pure diff for "Ask AI to change this recipe": which ingredient/step lines are new, reworded or removed.
// Used by the server (the `changes` summary), the app (preview highlights, keeping ids + checkmarks on save)
// and the website (transpiled by emm-blog-web/tools/build.mjs). Keep it free of React Native imports.
import { formatMinutes } from './quantity.js';
const norm = (s) => s
    .toLowerCase()
    .replace(/[‘’]/g, "'")
    .replace(/[^\p{L}\p{N}~/½¼¾⅓⅔⅛'.-]+/gu, ' ')
    .replace(/\s+/g, ' ')
    .trim();
const UNITS = new Set('cup cups c tbsp tbs tbsps tablespoon tablespoons tsp tsps teaspoon teaspoons lb lbs pound pounds oz ounce ounces g gr gram grams kg kilo kilos ml l liter liters litre litres cl dl pinch pinches dash dashes clove cloves can cans jar jars stick sticks slice slices piece pieces bunch handful large medium small about of a an to or and ~'.split(' '));
const STOP = new Set('the a an and or of to in into on with for until then it its is at by from over'.split(' '));
function words(s, kind) {
    const out = [];
    for (const w of norm(s).split(' ')) {
        const t = w.replace(/^[~'.-]+|[~'.-]+$/g, '');
        if (!t)
            continue;
        if (kind === 'ingredient') {
            // the ingredient's identity is its name (+ prep), not the amount
            if (/^[\d½¼¾⅓⅔⅛/.,-]+$/.test(t) || UNITS.has(t))
                continue;
        }
        else if (STOP.has(t))
            continue;
        out.push(t.length > 3 ? t.replace(/(es|s)$/, '') : t); // potatoes ≈ potato
    }
    return out;
}
/** Dice coefficient on word sets (0..1). */
function similarity(a, b) {
    if (!a.length || !b.length)
        return 0;
    const A = new Set(a);
    const B = new Set(b);
    let both = 0;
    for (const w of A)
        if (B.has(w))
            both++;
    return (2 * both) / (A.size + B.size);
}
/**
 * Line diff: exact matches (ignoring case/punctuation) are paired in order (LCS); the rest are paired by word
 * similarity ("reworded"); anything left is new (after) or removed (before).
 */
export function diffLines(before, after, kind = 'step') {
    const n = before.length;
    const m = after.length;
    const nb = before.map(norm);
    const na = after.map(norm);
    // LCS table
    const L = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));
    for (let i = n - 1; i >= 0; i--)
        for (let j = m - 1; j >= 0; j--)
            L[i][j] = nb[i] === na[j] ? L[i + 1][j + 1] + 1 : Math.max(L[i + 1][j], L[i][j + 1]);
    const pairA = new Array(m).fill(-1); // after index -> before index
    const usedB = new Array(n).fill(false);
    for (let i = 0, j = 0; i < n && j < m;) {
        if (nb[i] === na[j]) {
            pairA[j] = i;
            usedB[i] = true;
            i++;
            j++;
        }
        else if (L[i + 1][j] >= L[i][j + 1])
            i++;
        else
            j++;
    }
    // the same line moved elsewhere (e.g. to a new "part") is still the same line
    for (let j = 0; j < m; j++) {
        if (pairA[j] >= 0)
            continue;
        const i = nb.findIndex((x, k) => !usedB[k] && x === na[j]);
        if (i >= 0) {
            pairA[j] = i;
            usedB[i] = true;
        }
    }
    // reworded lines: best-scoring pairs first
    const threshold = kind === 'ingredient' ? 0.5 : 0.45;
    const wb = before.map((s) => words(s, kind));
    const wa = after.map((s) => words(s, kind));
    // an ingredient is mostly its name (before the first comma): "1 lb potatoes, halved" ≈ "2 lb potatoes, peeled"
    const head = (s) => (kind === 'ingredient' ? words(s.split(',')[0], kind) : []);
    const hb = before.map(head);
    const ha = after.map(head);
    const cands = [];
    for (let j = 0; j < m; j++) {
        if (pairA[j] >= 0)
            continue;
        for (let i = 0; i < n; i++) {
            if (usedB[i])
                continue;
            const s = Math.max(similarity(wb[i], wa[j]), similarity(hb[i], ha[j]));
            if (s >= threshold)
                cands.push([s, i, j]);
        }
    }
    cands.sort((x, y) => y[0] - x[0] || Math.abs(x[1] - x[2]) - Math.abs(y[1] - y[2]));
    const changed = new Set();
    for (const [, i, j] of cands) {
        if (usedB[i] || pairA[j] >= 0)
            continue;
        usedB[i] = true;
        pairA[j] = i;
        changed.add(j);
    }
    const lines = after.map((text, j) => {
        const i = pairA[j];
        if (i < 0)
            return { text, kind: 'new' };
        if (changed.has(j))
            return { text, kind: 'changed', from: i, was: before[i] };
        return { text, kind: 'same', from: i };
    });
    const removed = before.filter((_, i) => !usedB[i]);
    return { lines, removed };
}
/** The server's `changes` summary. */
export function summarizeChanges(before, after) {
    const ing = diffLines(before.ingredients, after.ingredients, 'ingredient');
    const st = diffLines(before.steps, after.steps, 'step');
    return {
        added: ing.lines.filter((l) => l.kind === 'new').map((l) => l.text),
        removed: ing.removed,
        changedIngredients: ing.lines.filter((l) => l.kind === 'changed').length,
        changedSteps: st.lines.filter((l) => l.kind !== 'same').length + st.removed.length,
    };
}
/** Small "also changed" lines for the preview: title, servings, times, tags, notes. */
export function metaChanges(before, after) {
    const out = [];
    if (before.title.trim() !== after.title.trim())
        out.push(`Name: ${after.title}`);
    if ((before.servings ?? null) !== (after.servings ?? null))
        out.push(`Serves ${before.servings ?? '–'} → ${after.servings ?? '–'}`);
    const t = (label, a, b) => {
        if ((a ?? null) !== (b ?? null))
            out.push(`${label} ${formatMinutes(a) ?? '–'} → ${formatMinutes(b) ?? '–'}`);
    };
    t('Prep', before.prepMin, after.prepMin);
    t('Cook', before.cookMin, after.cookMin);
    const low = (xs) => xs.map((x) => x.toLowerCase());
    const plus = low(after.tags).filter((x) => !low(before.tags).includes(x));
    const minus = low(before.tags).filter((x) => !low(after.tags).includes(x));
    if (plus.length || minus.length)
        out.push(`Tags: ${[...plus.map((x) => `+${x}`), ...minus.map((x) => `−${x}`)].join(' ')}`);
    if (before.notes.trim() !== after.notes.trim())
        out.push('Notes updated');
    return out;
}
/**
 * Apply new lines to existing rows, keeping the ids (and whatever else the row carries, e.g. checkmarks) of
 * unchanged lines; reworded lines keep their id but go through `onChanged`; new lines are made with `make`.
 */
export function reuseRows(before, after, kind, make, onChanged = (old, text) => ({ ...old, text })) {
    const d = diffLines(before.map((r) => r.text), after, kind);
    return d.lines.map((l) => (l.from === undefined ? make(l.text) : l.kind === 'same' ? { ...before[l.from], text: l.text } : onChanged(before[l.from], l.text)));
}
/** "Pot Roast" + "over mashed potatoes" -> "Pot Roast (over mashed potatoes)" (for "Save as a new recipe"). */
export function variantTitle(before, after, label) {
    const base = (after.trim() || before.trim() || 'Recipe').slice(0, 150);
    if (after.trim() && after.trim().toLowerCase() !== before.trim().toLowerCase())
        return base;
    const l = label.trim().replace(/^[(\s]+|[)\s.]+$/g, '').slice(0, 48);
    return l ? `${base} (${l})` : `${base} (my version)`;
}
