// GENERATED by tools/build.mjs from emm-blog-app/src/features/recipes/editTypes.ts. Do not edit.
// Shared contract for POST /api/recipe-edit ("Ask AI to change this recipe"), used by the API route, the app and
// the website. Pure types + constants only: no React Native or server imports here.
/** Size limits (checked on the server for input and output; the app trims before sending). */
export const EDIT_LIMITS = {
    request: 500,
    title: 200,
    ingredients: 80,
    ingredient: 500,
    steps: 60,
    step: 2000,
    notes: 5000,
    tags: 12,
    tag: 40,
    /** whole JSON body */
    body: 120000,
};
/** Rotating placeholder examples for the input. */
export const EDIT_EXAMPLES = ['make it dairy-free', 'serve it over mashed potatoes', 'halve the spice', 'make it in the slow cooker'];
/** Progress copy while the AI is thinking (rotates every ~2.5 s). */
export const EDIT_PROGRESS = ['Reading your recipe…', 'Thinking it through…', 'Rewriting the steps…', 'Almost there…'];
