// GENERATED by tools/build.mjs from emm-blog-app/src/features/recipes/importTypes.ts. Do not edit.
// Shared contract for POST /api/recipe-import (used by the API route AND the app).
// Pure types + constants only: no React Native or server imports here.
/** Header the app sends so random people can't burn the OpenAI budget (not a real secret, just a speed bump). */
export const IMPORT_TOKEN_HEADER = 'x-emm-import-token';
/** Tags the app already knows (keep in sync with tags.ts DEFAULT_TAGS). */
export const KNOWN_TAGS = ['breakfast', 'lunch', 'dinner', 'dessert', 'snack', 'drinks', 'baking', 'healthy', 'date night', 'comfort', 'quick'];
/** Emoji the editor offers (keep in sync with tags.ts FOOD_EMOJIS). */
export const KNOWN_EMOJIS = ['🍰', '🧁', '🍪', '🍩', '🥞', '🍝', '🍜', '🍛', '🍲', '🥗', '🍕', '🌮', '🍣', '🥘', '🍳', '🥐', '🍞', '🍓', '🍋', '🥑', '🍗', '🧋', '🍹', '☕'];
