// GENERATED by tools/build.mjs from emm-blog-app/src/features/recipes/parseRecipe.ts. Do not edit.
// "Import from text": paste any recipe (from a website, a note, a message) and we make a best guess
// at title / ingredients / steps / servings / times for her to review in the editor.
const H_ING = /^(ingredients?|what you('|’)?ll need|you('|’)?ll need|you need|shopping list)\b[\s:.-]*$/i;
const H_STEP = /^(steps?|method|directions?|instructions?|preparation|how to( make it)?|recipe)\b[\s:.-]*$/i;
const H_NOTES = /^(notes?|tips?|variations?)\b[\s:.-]*$/i;
const BULLET = /^\s*(?:[-–—•*·▢□☐○●◦✓✔]+|\(?\d{1,2}[.)]|step\s*\d+[:.)]?)\s*/i;
const HAS_NUM_START = /^\s*[-–•*]?\s*(\d|[½¼¾⅓⅔⅛])/;
function minutesIn(s) {
    const h = /(\d+)\s*(?:h|hr|hrs|hours?)/i.exec(s);
    const m = /(\d+)\s*(?:m|min|mins|minutes?)\b/i.exec(s);
    if (!h && !m)
        return null;
    return (h ? +h[1] * 60 : 0) + (m ? +m[1] : 0);
}
export function parseRecipeText(raw) {
    const lines = raw
        .replace(/\r/g, '')
        .split('\n')
        .map((l) => l.trim())
        .filter((l) => l.length > 0);
    const out = { title: '', ingredients: [], steps: [], notes: '', servings: null, prepMin: null, cookMin: null };
    let section = 'none';
    const loose = [];
    const notes = [];
    for (const line of lines) {
        if (H_ING.test(line)) {
            section = 'ing';
            continue;
        }
        if (H_STEP.test(line)) {
            section = 'step';
            continue;
        }
        if (H_NOTES.test(line)) {
            section = 'notes';
            continue;
        }
        const serves = /^(?:serves|servings?|yield|makes|portions?)\s*:?\s*(\d+)/i.exec(line);
        if (serves) {
            out.servings = +serves[1];
            continue;
        }
        if (/^prep(?:aration)?(?:\s*time)?\s*:/i.test(line)) {
            out.prepMin = minutesIn(line);
            continue;
        }
        if (/^(?:cook(?:ing)?|bake|baking)(?:\s*time)?\s*:/i.test(line)) {
            out.cookMin = minutesIn(line);
            continue;
        }
        if (/^total(?:\s*time)?\s*:/i.test(line))
            continue;
        if (!out.title && section === 'none') {
            out.title = line.replace(BULLET, '').replace(/[#*_]/g, '').trim();
            continue;
        }
        const clean = line.replace(BULLET, '').trim();
        if (!clean)
            continue;
        if (section === 'ing')
            out.ingredients.push(clean);
        else if (section === 'step')
            out.steps.push(clean);
        else if (section === 'notes')
            notes.push(clean);
        else
            loose.push(line);
    }
    // No headers? Guess line by line: short lines starting with a number = ingredients, sentences = steps.
    for (const line of loose) {
        const clean = line.replace(BULLET, '').trim();
        const numbered = /^\s*(?:\d{1,2}[.)]|step\s*\d+)/i.test(line);
        const sentence = clean.length > 60 || /[.!]$/.test(clean);
        if (!numbered && (HAS_NUM_START.test(line) || (!sentence && clean.split(' ').length <= 6)))
            out.ingredients.push(clean);
        else
            out.steps.push(clean);
    }
    // One long paragraph of method? Split into sentences.
    if (out.steps.length === 1 && out.steps[0].length > 160) {
        out.steps = out.steps[0].split(/(?<=[.!])\s+(?=[A-Z])/).map((s) => s.trim()).filter(Boolean);
    }
    out.notes = notes.join('\n');
    if (!out.title)
        out.title = 'Imported recipe';
    return out;
}
