// GENERATED by tools/build.mjs from emm-blog-app/src/features/recipes/quantity.ts. Do not edit.
// Ingredient quantity parsing + scaling. Handles "2 cups", "1/2 tsp", "1 1/2 cups", "1½", "200g",
// "2.5 kg", "1,5 l", ranges like "2-3 eggs" / "2 to 3".
const VULGAR = {
    '½': 1 / 2, '⅓': 1 / 3, '⅔': 2 / 3, '¼': 1 / 4, '¾': 3 / 4, '⅕': 1 / 5, '⅖': 2 / 5, '⅗': 3 / 5, '⅘': 4 / 5,
    '⅙': 1 / 6, '⅚': 5 / 6, '⅛': 1 / 8, '⅜': 3 / 8, '⅝': 5 / 8, '⅞': 7 / 8,
};
const V = Object.keys(VULGAR).join('');
// order matters: mixed numbers and fractions before plain decimals
const NUM = `(?:\\d+\\s+\\d+\\/\\d+|\\d+\\/\\d+|\\d*\\s?[${V}]|\\d+(?:[.,]\\d+)?)`;
const LEAD = new RegExp(`^(\\s*)(${NUM})(?:\\s*(?:-|–|to)\\s*(${NUM}))?(.*)$`, 's');
export function parseNumber(s) {
    const t = s.trim();
    let m = /^(\d+)\s+(\d+)\/(\d+)$/.exec(t);
    if (m)
        return +m[1] + +m[2] / (+m[3] || 1);
    m = /^(\d+)\/(\d+)$/.exec(t);
    if (m)
        return +m[1] / (+m[2] || 1);
    m = new RegExp(`^(\\d*)\\s?([${V}])$`).exec(t);
    if (m)
        return (m[1] ? +m[1] : 0) + VULGAR[m[2]];
    m = /^(\d+)(?:[.,](\d+))?$/.exec(t);
    if (m)
        return parseFloat(`${m[1]}.${m[2] ?? '0'}`);
    return null;
}
const METRIC = /^\s*(g|gr|grams?|kg|kilos?|mg|ml|millilit(?:er|re)s?|cl|dl|l|lit(?:er|re)s?)\b/i;
const FRACTIONS = [
    [0, ''], [1 / 8, '1/8'], [1 / 4, '1/4'], [1 / 3, '1/3'], [3 / 8, '3/8'], [1 / 2, '1/2'], [5 / 8, '5/8'], [2 / 3, '2/3'], [3 / 4, '3/4'], [7 / 8, '7/8'], [1, ''],
];
/** Pretty-print a quantity: fractions for cups/spoons, decimals for metric, whole numbers when big. */
export function formatNumber(n, metric = false) {
    if (n <= 0)
        return '0';
    if (n >= 20 || (metric && n >= 10))
        return String(Math.round(n));
    if (metric)
        return String(Math.round(n * 10) / 10);
    let whole = Math.floor(n);
    const frac = n - whole;
    let best = FRACTIONS[0];
    for (const f of FRACTIONS)
        if (Math.abs(f[0] - frac) < Math.abs(best[0] - frac))
            best = f;
    if (Math.abs(best[0] - frac) > 0.05)
        return String(Math.round(n * 10) / 10);
    if (best[0] === 1) {
        whole += 1;
        best = FRACTIONS[0];
    }
    if (!best[1])
        return String(whole);
    return whole ? `${whole} ${best[1]}` : best[1];
}
export function splitLeading(text) {
    const m = LEAD.exec(text);
    if (!m)
        return null;
    const a = parseNumber(m[2]);
    if (a === null)
        return null;
    const b = m[3] ? parseNumber(m[3]) : null;
    return { lead: m[1], a, b, rest: m[4] };
}
// "1 cup" ×2 -> "2 cups", "1 1/2 cups" ×0.5 -> "3/4 cup"
const PLURALS = {
    cup: 'cups', tablespoon: 'tablespoons', teaspoon: 'teaspoons', pound: 'pounds', ounce: 'ounces', clove: 'cloves', can: 'cans',
    pinch: 'pinches', dash: 'dashes', slice: 'slices', stick: 'sticks', handful: 'handfuls', piece: 'pieces', jar: 'jars', bunch: 'bunches',
    package: 'packages', packet: 'packets', bag: 'bags', sprig: 'sprigs', quart: 'quarts', pint: 'pints', head: 'heads', scoop: 'scoops',
};
const SINGULARS = Object.fromEntries(Object.entries(PLURALS).map(([one, many]) => [many, one]));
function matchUnitCount(rest, amount) {
    const m = /^(\s+)([a-z]+)\b/i.exec(rest);
    if (!m)
        return rest;
    const word = m[2].toLowerCase();
    const next = amount > 1 ? PLURALS[word] : SINGULARS[word];
    if (!next)
        return rest;
    const cased = m[2][0] === m[2][0].toUpperCase() ? next[0].toUpperCase() + next.slice(1) : next;
    return m[1] + cased + rest.slice(m[0].length);
}
/** Scale the leading quantity of an ingredient line. Lines without a number are returned as-is. */
export function scaleIngredient(text, factor) {
    if (factor === 1 || !Number.isFinite(factor) || factor <= 0)
        return text;
    const q = splitLeading(text);
    if (!q)
        return text;
    const metric = METRIC.test(q.rest);
    const a = formatNumber(q.a * factor, metric);
    const b = q.b !== null ? formatNumber(q.b * factor, metric) : null;
    return `${q.lead}${a}${b ? `-${b}` : ''}${matchUnitCount(q.rest, (q.b ?? q.a) * factor)}`;
}
const UNITS = [
    'cups', 'cup', 'c', 'tablespoons', 'tablespoon', 'tbsp', 'tbs', 'tbl', 'teaspoons', 'teaspoon', 'tsp', 'grams', 'gram', 'gr', 'g', 'kilograms',
    'kilogram', 'kilos', 'kilo', 'kg', 'mg', 'milliliters', 'millilitres', 'milliliter', 'millilitre', 'ml', 'cl', 'dl', 'liters', 'litres', 'liter',
    'litre', 'l', 'ounces', 'ounce', 'oz', 'fl oz', 'pounds', 'pound', 'lbs', 'lb', 'pinches', 'pinch', 'dashes', 'dash', 'cloves', 'clove', 'cans',
    'can', 'tins', 'tin', 'packs', 'pack', 'packets', 'packet', 'packages', 'package', 'slices', 'slice', 'sticks', 'stick', 'bunches', 'bunch',
    'handfuls', 'handful', 'pieces', 'piece', 'pcs', 'jars', 'jar', 'bottles', 'bottle', 'sprigs', 'sprig', 'drops', 'drop', 'quarts', 'quart',
    'pints', 'pint', 'bags', 'bag', 'boxes', 'box', 'heads', 'head', 'scoops', 'scoop', 'sheets', 'sheet',
].sort((x, y) => y.length - x.length);
const UNIT_RE = new RegExp(`^\\s*(${UNITS.map((u) => u.replace(' ', '\\s')).join('|')})\\.?(?=\\s|$)`, 'i');
/**
 * Turn an ingredient line into a shopping item:
 *   "2 cups flour, sifted" -> { text: 'Flour', qty: '2 cups' }
 *   "1 onion, finely chopped" -> { text: 'Onion', qty: '1' }
 */
export function ingredientToItem(line) {
    const q = splitLeading(line);
    let name = line;
    let qty = null;
    if (q) {
        let rest = q.rest;
        const metric = METRIC.test(rest);
        qty = formatNumber(q.a, metric) + (q.b !== null ? `-${formatNumber(q.b, metric)}` : '');
        const u = UNIT_RE.exec(rest);
        if (u) {
            qty += (/^\s/.test(rest) ? ' ' : '') + u[1];
            rest = rest.slice(u[0].length);
        }
        name = rest;
    }
    name = name
        .replace(/\([^)]*\)/g, ' ')
        .replace(/,.*$/, '')
        .replace(/^\s*(of|x)\s+/i, '')
        .replace(/\s+/g, ' ')
        .trim();
    if (!name)
        name = line.trim();
    return { text: name.charAt(0).toUpperCase() + name.slice(1), qty: qty && qty !== '1' ? qty : qty };
}
const TIME_RE = /(\d+(?:[.,]\d+)?|[½¼¾])\s*(?:(?:-|–|to)\s*(\d+(?:[.,]\d+)?)\s*)?(hours?|hrs?|h|minutes?|mins?|m|seconds?|secs?|s)\b/gi;
/** Find "10 minutes", "1-2 hrs", "30 sec" in a step. Uses the lower end of a range. */
export function findTimers(step) {
    const out = [];
    for (const m of step.matchAll(TIME_RE)) {
        const n = VULGAR[m[1]] ?? parseFloat(m[1].replace(',', '.'));
        const unit = m[3].toLowerCase();
        // bare "m"/"s"/"h" only count when glued to the number ("10m"), to avoid false hits
        if (unit.length === 1 && /\s/.test(m[0].slice(m[1].length, m[0].length - 1)))
            continue;
        const mult = unit.startsWith('h') ? 3600 : unit.startsWith('s') ? 1 : 60;
        const seconds = Math.round(n * mult);
        if (seconds < 5 || seconds > 24 * 3600)
            continue;
        out.push({ label: m[0].trim(), seconds });
        if (out.length >= 3)
            break;
    }
    return out;
}
export function formatClock(sec) {
    const s = Math.max(0, Math.ceil(sec));
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    const r = s % 60;
    const mm = String(m).padStart(h ? 2 : 1, '0');
    return h ? `${h}:${mm}:${String(r).padStart(2, '0')}` : `${mm}:${String(r).padStart(2, '0')}`;
}
export function formatMinutes(min) {
    if (!min)
        return null;
    if (min < 60)
        return `${min} min`;
    const h = Math.floor(min / 60);
    const m = min % 60;
    return m ? `${h} h ${m} min` : `${h} h`;
}
