// GENERATED by tools/build.mjs from emm-blog-app/src/features/recipes/source.ts. Do not edit.
// Imported recipes remember where they came from as the last lines of `notes` (no schema change):
//   "...her notes...\n\nFrom: Garlic Butter Salmon · YouTube\nhttps://youtu.be/abc"
const SOURCE_RE = /(?:^|\n+)From: ([^\n]*)\n(https?:\/\/\S+)\s*$/;
export function withSource(notes, title, url) {
    if (!url)
        return notes;
    const line = `From: ${(title || hostOf(url)).replace(/\s+/g, ' ').trim()}\n${url}`;
    return notes.trim() ? `${notes.trim()}\n\n${line}` : line;
}
export function splitSource(notes) {
    const m = SOURCE_RE.exec(notes);
    if (!m)
        return { notes, source: null };
    return { notes: notes.slice(0, m.index).trim(), source: { title: m[1].trim() || hostOf(m[2]), url: m[2] } };
}
export function hostOf(url) {
    try {
        return new URL(url).hostname.replace(/^www\./, '');
    }
    catch {
        return url;
    }
}
