// GENERATED by tools/build.mjs from emm-blog-app/src/features/recipes/stepIngredients.ts. Do not edit.
// Ingredients per step ("measure as you go"): which ingredient lines each step uses, and how much.
// Pure TS (no React Native imports): the app, the self-test, node and the website (tools/build.mjs) run it as-is.
//
//   matchStepIngredients(ingredients, steps)  instant, free, on-device guess (word matching, see below)
//   stepIngredientsFor(recipe)                the stored AI mapping when it still fits the texts, else the local guess
//   stepIngLines(ingredients, uses, factor)   display rows: { qty: '2 tbsp', name: 'butter' } (scaled)
//
// Local matching: each ingredient line becomes its core name ("2 cups low-sodium chicken stock, divided" ->
// "chicken broth": amount, unit, prep words and asides dropped, plurals folded, synonyms like stock/broth or
// scallions/green onions unified) plus shorter "terms" (the head noun "broth", the first word when it's a food
// on its own: "chicken" of "chicken thighs"). Steps are split into whole words (so "oil" never hits "boil" and
// "salt" never hits "unsalted"), the longest term wins where terms overlap, and a word that fits several
// lines ("oil" with olive + sesame oil) goes to the likeliest one. Generic words map to groups when obvious
// ("the dry ingredients", "the spices", "the herbs", "the vegetables", "the sauce" for lines marked "for the
// sauce"), skipping lines an earlier step already used. "half the butter", "1 cup of the broth" and "the
// remaining butter" give partial amounts. An ingredient that comes back in a later step is only listed again
// when that use is partial or it's something usually split (salt, oil, butter, water…).
import { aisleOf, exactItem, keyOf, matchItem } from '../grocery/catalog.js';
import { cleanIngredientName, parseQty } from '../grocery/parse.js';
import { ingredientToItem, scaleIngredient } from './quantity.js';
import { stepIngsSig, storedStepIngs } from './stepIngTypes.js';
const WORD_RE = /[\p{L}\p{N}]+(?:['’][\p{L}]+)*/gu;
function rawTokens(text) {
    const out = [];
    for (const m of text.matchAll(WORD_RE)) {
        const w = keyOf(m[0]);
        if (w && !w.includes(' '))
            out.push({ w, s: m.index ?? 0, e: (m.index ?? 0) + m[0].length });
    }
    return out;
}
// same-thing words, folded on both sides (ingredient names and step text); multi-word first
const PHRASES = [
    ['heavy whipping cream', 'heavy cream'],
    ['whipping cream', 'heavy cream'],
    ['double cream', 'heavy cream'],
    ['scallion', 'green onion'],
    ['spring onion', 'green onion'],
    ['garbanzo bean', 'chickpea'],
    ['garbanzo', 'chickpea'],
    ['confectioner sugar', 'powdered sugar'],
    ['confectioners sugar', 'powdered sugar'],
    ['icing sugar', 'powdered sugar'],
    ['corn starch', 'cornstarch'],
    ['cornflour', 'cornstarch'],
    ['bicarbonate of soda', 'baking soda'],
    ['bicarb soda', 'baking soda'],
    ['bicarb', 'baking soda'],
    ['parmigiano reggiano', 'parmesan'],
    ['parmigiano', 'parmesan'],
    ['beef mince', 'ground beef'],
    ['minced beef', 'ground beef'],
    ['capsicum', 'bell pepper'],
    ['courgette', 'zucchini'],
    ['aubergine', 'eggplant'],
    ['prawn', 'shrimp'],
    ['chile', 'chili'],
    ['chilli', 'chili'],
    ['yoghurt', 'yogurt'],
    ['stock', 'broth'],
    ['caster sugar', 'sugar'],
    ['granulated sugar', 'sugar'],
    ['white sugar', 'sugar'],
]
    .map(([a, b]) => [a.split(' ').map(keyOf), b.split(' ').map(keyOf)])
    .sort((x, y) => y[0].length - x[0].length);
function fold(toks) {
    const out = [];
    for (let p = 0; p < toks.length;) {
        let hit = null;
        for (const ph of PHRASES) {
            const [from] = ph;
            if (p + from.length > toks.length)
                continue;
            if (from.every((w, k) => toks[p + k].w === w)) {
                hit = ph;
                break;
            }
        }
        // "stock pot" is a pot
        if (hit && hit[0][0] === 'stock' && toks[p + 1]?.w === 'pot')
            hit = null;
        if (!hit) {
            out.push(toks[p]);
            p++;
            continue;
        }
        const s = toks[p].s;
        const e = toks[p + hit[0].length - 1].e;
        for (const w of hit[1])
            out.push({ w, s, e });
        p += hit[0].length;
    }
    return out;
}
const words = (text) => fold(rawTokens(text));
// never an ingredient on their own (describe one, or are a unit / container / part)
const NOT_ALONE = new Set(('red green yellow white black brown dark light golden sweet hot spicy mild dry dried whole sea kosher table plain unsalted salted low sodium fat free ' +
    'reduced heavy sour flat italian fine coarse ground large small medium extra virgin raw frozen canned cooked uncooked instant quick old fashioned rolled ' +
    'boneless skinless bone skin natural pure baby young new mixed smoked sharp aged soft firm silken thick thin long short fresh organic toasted roasted ' +
    'and or of the with for in a an to your into some more less plus few each other any all purpose self rising multi ' +
    'cup tablespoon teaspoon tbsp tsp oz ounce lb pound gram kg ml liter litre quart pint gallon inch cm ' +
    'sauce powder seed leaf paste extract juice mix mixture seasoning clove piece slice stick can jar tin sprig head bunch pinch dash cube chunk strip ' +
    'wedge round part topping filling crust dough batter glaze marinade dressing frosting icing slurry rub garnish serving taste need optional')
    .split(' ')
    .map(keyOf));
// heads that name something made FROM another food ("chicken" alone means the chicken, not the broth)
const DERIVED = new Set('broth sauce powder oil juice paste extract seasoning bouillon zest flake vinegar milk water syrup jam puree starch spice salt cream wine'.split(' ').map(keyOf));
// usually split across steps (salt the water, then the sauce…): listed again when they come back
const SPLITTABLE = new Set('salt pepper oil butter water broth sugar flour cream milk juice cheese'.split(' ').map(keyOf));
const allowSingle = (w) => w.length >= 3 && !NOT_ALONE.has(w) && !/^\d/.test(w);
const LABEL_WORDS = 'sauce|marinade|dressing|glaze|topping|filling|batter|frosting|icing|crust|slurry|gravy|rub|garnish|mash|streusel|crumble';
const LABEL_PREFIX = /^\s*(?:for\s+(?:the\s+)?)?([a-z][a-z ]{1,24}?)\s*:\s*(.+)$/i;
const LABEL_INLINE = new RegExp(`\\bfor (?:the )?(${LABEL_WORDS})\\b`, 'i');
const SPLIT_HINT = /\b(divided|plus more|plus extra|to taste|for (?:serving|garnish|sprinkling|dusting|topping)|separated|as needed)\b/i;
const DRY_RE = /\b(flour|baking soda|baking powder|salt|cocoa|cornstarch|cornmeal|polenta|oats?|yeast|xanthan|cinnamon|nutmeg|allspice|cardamom|ground ginger|ground cloves|pumpkin pie spice|espresso powder|milk powder|semolina)\b/i;
const WET_RE = /\b(eggs?|egg yolks?|egg whites?|milk|buttermilk|oil|melted|vanilla|extract|yogurt|sour cream|honey|maple syrup|molasses|water|coffee|cream|applesauce|mashed bananas?|juice)\b/i;
const PLAIN_SEASONING = /^(?:(?:kosher|sea|table|fine|flaky)\s+)?salt$|^(?:black\s+|white\s+)?pepper(?:corns?)?$|^salt and pepper$/i;
const VEG_SUBS = new Set(['Vegetables', 'Leafy greens', 'Root veg', 'Onions & garlic', 'Peppers', 'Squash', 'Mushrooms']);
const MEAT_SUBS = new Set(['Chicken', 'Beef', 'Pork', 'Turkey', 'Fish', 'Seafood']);
function termsFor(nameToks, out, only) {
    const n = nameToks.length;
    if (!n)
        return;
    const add = (toks, kind) => {
        if (only)
            kind = only;
        if (!toks.length || (toks.length === 1 && !allowSingle(toks[0])))
            return;
        if (kind < 3 && toks.every((w) => NOT_ALONE.has(w)))
            return; // "italian seasoning" is fine as the whole name
        out.push({ toks, kind });
    };
    add(nameToks, 3);
    for (let k = 1; k < n; k++)
        add(nameToks.slice(k), 2);
    if (n >= 3)
        for (let j = 0; j < n - 1; j++)
            add([...nameToks.slice(0, j), ...nameToks.slice(j + 1)], 2);
    if (n >= 2 && allowSingle(nameToks[0]) && exactItem(nameToks[0]))
        add([nameToks[0]], 1);
}
function buildInfo(line, i) {
    let t = line.replace(/^\s*[~≈]\s*/, '');
    let label = null;
    const lp = LABEL_PREFIX.exec(t);
    if (lp && !/\d/.test(lp[1])) {
        label = keyOf(lp[1]).split(' ').pop() ?? null;
        t = lp[2];
    }
    const li = LABEL_INLINE.exec(line);
    if (li)
        label = keyOf(li[1]);
    // "2 tbsp cornstarch mixed with 2 tbsp cold water" is the cornstarch (the water shouldn't match "salted water")
    const noParens = t
        .replace(/\([^)]*\)/g, ' ')
        .replace(/\s+(?:mixed|dissolved|whisked|combined|stirred|blended)\s+(?:with|in|into)\s+.*$/i, '')
        .replace(/\s+/g, ' ')
        .trim();
    const item = ingredientToItem(noParens);
    const core = cleanIngredientName(item.text).toLowerCase();
    const alts = /half[- ]and[- ]half/.test(core)
        ? [core]
        : core
            .split(/\s+(?:and|or|&)\s+|\s*\/\s*/)
            .map((x) => x.trim())
            .filter(Boolean)
            .slice(0, 3);
    const terms = [];
    let toks = [];
    for (const alt of alts) {
        const at = words(alt)
            .map((x) => x.w)
            .filter((w) => !/^\d/.test(w));
        if (!toks.length)
            toks = at;
        termsFor(at, terms);
    }
    // the catalog's other names for the same thing ("scallions" = "green onions")
    const cat = exactItem(core);
    // (not combos like Salt's "salt and pepper": that would swallow the pepper)
    if (cat)
        for (const alias of [cat.name, ...cat.syn])
            if (!/\s(?:and|or|&)\s/i.test(alias))
                termsFor(words(alias).map((x) => x.w), terms);
    const head = toks[toks.length - 1] ?? '';
    const hit = cat ?? matchItem(core);
    // "flank steak" / "chuck roast" is the beef, "salmon fillets" the fish
    if (hit && MEAT_SUBS.has(hit.sub))
        termsFor([keyOf(hit.sub)], terms, 1);
    const lower = line.toLowerCase();
    return {
        i,
        line,
        toks,
        terms,
        head,
        derived: DERIVED.has(head),
        label,
        qty: item.qty,
        splittable: SPLIT_HINT.test(line) || SPLITTABLE.has(head),
        dry: DRY_RE.test(core) && !/\b(melted|oil|extract)\b/.test(lower),
        wet: WET_RE.test(lower) && !/\b(flour|powder|cocoa)\b/.test(core),
        spice: aisleOf(core) === 'spices' && !PLAIN_SEASONING.test(core),
        herb: hit?.sub === 'Herbs',
        veg: !!hit && hit.aisle === 'produce' && VEG_SUBS.has(hit.sub) && !/\b(garlic|ginger)\b/.test(core),
    };
}
function findMentions(toks, index) {
    const raw = new Map();
    for (let p = 0; p < toks.length; p++) {
        const entries = index.get(toks[p].w);
        if (!entries)
            continue;
        for (const en of entries) {
            const len = en.toks.length;
            if (p + len > toks.length || !en.toks.every((w, k) => toks[p + k].w === w))
                continue;
            // "cream the butter and sugar" is a verb
            if (len === 1 && toks[p].w === 'cream' && /^(the|together|butter|until|it)$/.test(toks[p + 1]?.w ?? ''))
                continue;
            const key = `${p}:${len}`;
            const m = raw.get(key);
            if (!m)
                raw.set(key, { p, len, cands: [en.ing], kind: en.kind, s: toks[p].s, e: toks[p + len - 1].e });
            else if (en.kind > m.kind) {
                m.kind = en.kind;
                m.cands = [en.ing];
            }
            else if (en.kind === m.kind && !m.cands.includes(en.ing))
                m.cands.push(en.ing);
        }
    }
    const sorted = [...raw.values()].sort((a, b) => b.len - a.len || b.kind - a.kind || a.p - b.p);
    const taken = [];
    const out = [];
    for (const m of sorted) {
        let free = true;
        for (let k = m.p; k < m.p + m.len; k++)
            if (taken[k])
                free = false;
        if (!free)
            continue;
        for (let k = m.p; k < m.p + m.len; k++)
            taken[k] = true;
        out.push(m);
    }
    return out.sort((a, b) => a.p - b.p);
}
const NUM = String.raw `(?:\d+\s+\d+\/\d+|\d+\/\d+|\d*\s?[½⅓⅔¼¾⅛]|\d+(?:\.\d+)?)`;
const UNIT = String.raw `(?:cups?|c|tablespoons?|tbsps?|tbs|T|teaspoons?|tsps?|t|oz|ounces?|lbs?|pounds?|g|grams?|kg|ml|l|liters?|litres?|cloves?|pinch(?:es)?|dash(?:es)?|handfuls?|slices?|sticks?|cans?|sprigs?|stalks?|pieces?|quarts?|pints?)`;
const QTY_BEFORE = new RegExp(`(?:^|[\\s(])(${NUM}(?:\\s*(?:-|–|to)\\s*${NUM})?(?:\\s*${UNIT}\\.?)?)\\s+(?:of\\s+)?(?:the\\s+)?(?:[a-z-]+\\s+)?$`, 'i');
const FRACTIONS = [
    [/(?:^|\s)(?:half|one[- ]half|1\/2|½)$/i, 1 / 2],
    [/(?:^|\s)(?:a|one)[- ]third$|(?:^|\s)(?:1\/3|⅓)$/i, 1 / 3],
    [/(?:^|\s)two[- ]thirds$|(?:^|\s)(?:2\/3|⅔)$/i, 2 / 3],
    [/(?:^|\s)(?:a|one)[- ]quarter$|(?:^|\s)(?:1\/4|¼)$/i, 1 / 4],
    [/(?:^|\s)three[- ]quarters$|(?:^|\s)(?:3\/4|¾)$/i, 3 / 4],
];
const FRACTION_BEFORE = /((?:^|\s)[\w½⅓⅔¼¾/-]+(?:[- ]\w+)?)\s+(?:of\s+)?(?:the\s+)?(?:[a-z-]+\s+)?$/i;
const REMAINING_BEFORE = /(?:remaining|rest of (?:the|your)|leftover|reserved|other half of (?:the|your)|the other half of)\s+(?:[a-z-]+\s+)?$/i;
function partialBefore(step, at) {
    const before = step.slice(Math.max(0, at - 48), at);
    if (REMAINING_BEFORE.test(before))
        return { remaining: true };
    const q = QTY_BEFORE.exec(before);
    if (q && !/\d\s*(?:°|degrees|minutes?|mins?|hours?|seconds?|inch|-inch|x)\s*$/i.test(q[1])) {
        const amt = q[1].replace(/\s+/g, ' ').trim();
        if (/^[½⅓⅔¼¾⅛]$/.test(amt) || /^\d+\/\d+$/.test(amt)) {
            // "½ the butter": a bare fraction reads as a portion, not a count
            const f = FRACTIONS.find(([re]) => re.test(` ${amt}`));
            if (f)
                return { frac: f[1] };
        }
        return { amount: amt };
    }
    const f = FRACTION_BEFORE.exec(before);
    if (f) {
        const hit = FRACTIONS.find(([re]) => re.test(f[1].trimEnd()));
        if (hit)
            return { frac: hit[1] };
    }
    return null;
}
/** A fraction of the line's amount ("4 tbsp" × ½ -> "2 tbsp"); words when the line has no amount. */
function fractionOf(info, f) {
    if (info.qty)
        return scaleIngredient(info.qty, f);
    return f === 0.5 ? 'half' : f === 0.25 ? 'a quarter' : f === 0.75 ? 'three quarters' : f < 0.5 ? 'a third' : 'two thirds';
}
/** How much of the line an explicit amount is (same unit only), or null. */
function ratioOf(info, amount) {
    const a = parseQty(amount);
    const b = parseQty(info.qty);
    if (!a || !b || b.n <= 0 || a.unit !== b.unit)
        return null;
    return a.n / b.n;
}
const GROUPS = [
    { re: /\b(?:dry ingredients|flour mixture|dry mix(?:ture)?)\b/gi, pick: (x) => x.dry },
    { re: /\bwet ingredients\b/gi, pick: (x) => x.wet },
    { re: /\b(?:the|all the|your)\s+(?:spices|seasonings|spice (?:mix|mixture|blend))\b/gi, pick: (x) => x.spice },
    { re: /\bthe\s+(?:fresh\s+)?herbs\b/gi, pick: (x) => x.herb },
    { re: /\bthe\s+(?:vegetables|veggies|veg)\b/gi, pick: (x) => x.veg },
    { re: new RegExp(`\\b(?:the\\s+(${LABEL_WORDS})\\b|(${LABEL_WORDS})\\s+ingredients\\b)`, 'gi'), label: true },
];
/**
 * For every step, the ingredient lines it uses (ordered by first mention in the step), with `amount` when the step
 * clearly uses only part of a line. Pure and fast (a recipe takes well under a millisecond after the first call).
 */
export function matchStepIngredients(ingredients, steps) {
    const infos = ingredients.map(buildInfo);
    const index = new Map();
    for (const info of infos) {
        for (const t of info.terms) {
            const arr = index.get(t.toks[0]) ?? [];
            if (!arr.some((x) => x.ing === info.i && x.toks.join(' ') === t.toks.join(' ') && x.kind >= t.kind))
                arr.push({ toks: t.toks, ing: info.i, kind: t.kind });
            index.set(t.toks[0], arr);
        }
    }
    const perStep = steps.map((s) => findMentions(words(s), index));
    // lines named unambiguously somewhere: an ambiguous word ("oil") prefers a line that isn't
    const named = new Set();
    for (const ms of perStep)
        for (const m of ms)
            if (m.cands.length === 1)
                named.add(m.cands[0]);
    const used = new Set(); // used by an earlier step
    // a word that fits several lines: not a derived thing ("chicken" isn't the broth), not used yet ("the salt" in
    // the mash step is the mash's salt), the plainest name, not named elsewhere, then list order
    const pick = (cands) => [...cands].sort((a, b) => {
        const A = infos[a];
        const B = infos[b];
        return +A.derived - +B.derived || +used.has(a) - +used.has(b) || A.toks.length - B.toks.length || +named.has(a) - +named.has(b) || a - b;
    })[0];
    const frac = new Map(); // portion used so far (when known)
    const result = [];
    steps.forEach((step, si) => {
        const uses = [];
        const here = new Set();
        // group phrases ("the flour mixture", "the dry ingredients") aren't mentions of their words' ingredients
        const lower = step.toLowerCase();
        const groupHits = [];
        for (const g of GROUPS)
            for (const m of lower.matchAll(g.re))
                groupHits.push({ g, m });
        const inGroup = (m) => groupHits.some(({ m: h }) => m.s >= (h.index ?? 0) && m.e <= (h.index ?? 0) + h[0].length);
        for (const m of perStep[si]) {
            if (inGroup(m))
                continue;
            const i = m.cands.length === 1 ? m.cands[0] : pick(m.cands);
            if (here.has(i))
                continue;
            const info = infos[i];
            const part = partialBefore(step, m.s);
            let amount;
            if (part?.remaining) {
                const f = frac.get(i) ?? 0;
                if (f > 0 && f < 0.999)
                    amount = fractionOf(info, 1 - f);
                frac.set(i, 1);
            }
            else if (part?.frac) {
                amount = fractionOf(info, part.frac);
                frac.set(i, Math.min(1, (frac.get(i) ?? 0) + part.frac));
            }
            else if (part?.amount) {
                const r = ratioOf(info, part.amount);
                if (r === null || r < 0.999)
                    amount = part.amount;
                if (r !== null)
                    frac.set(i, Math.min(1, (frac.get(i) ?? 0) + r));
            }
            else if (used.has(i)) {
                const f = frac.get(i) ?? 0;
                if (f > 0 && f < 0.999) {
                    amount = fractionOf(info, 1 - f); // "half the butter" earlier, "the butter" now = the rest
                    frac.set(i, 1);
                }
                else if (!info.splittable)
                    continue; // "return the chicken to the pan": already measured
            }
            here.add(i);
            uses.push({ i, ...(amount ? { amount } : {}), at: m.s, sub: 0 });
        }
        // "the dry ingredients", "the spices", "the sauce" (lines marked for the sauce)…
        for (const { g, m } of groupHits) {
            const label = 'label' in g ? keyOf(m[1] ?? m[2] ?? '') : null;
            const members = infos.filter((x) => !used.has(x.i) && !here.has(x.i) && (label ? x.label === label : 'pick' in g && g.pick(x)));
            members.forEach((x, k) => {
                here.add(x.i);
                uses.push({ i: x.i, at: m.index ?? 0, sub: k + 1 });
            });
        }
        uses.sort((a, b) => a.at - b.at || a.sub - b.sub);
        for (const u of uses)
            used.add(u.i);
        result.push(uses.map(({ at: _a, sub: _s, ...u }) => u));
    });
    // a line used in several steps without saying how much each time: flag those uses
    const count = new Map();
    for (const uses of result)
        for (const u of uses)
            count.set(u.i, (count.get(u.i) ?? 0) + 1);
    for (const uses of result)
        for (const u of uses)
            if (!u.amount && (count.get(u.i) ?? 0) > 1)
                u.shared = true;
    return result;
}
const memo = new Map();
/** The mapping to show: the stored AI one when it still matches the recipe's texts, else the local guess. Memoized. */
export function stepIngredientsFor(recipe) {
    const stored = storedStepIngs(recipe.ingredients, recipe.steps);
    if (stored)
        return { map: stored, source: 'ai' };
    const ings = recipe.ingredients.map((i) => i.text);
    const steps = recipe.steps.map((s) => s.text);
    const key = stepIngsSig(ings, steps);
    const hit = memo.get(key);
    if (hit)
        return hit;
    const out = { map: matchStepIngredients(ings, steps), source: 'local' };
    if (memo.size > 40)
        memo.clear();
    memo.set(key, out);
    return out;
}
/** Display rows for one step's uses, amounts scaled by `factor` (partial amounts too). */
export function stepIngLines(ingredients, uses, factor = 1) {
    const out = [];
    for (const u of uses) {
        const line = ingredients[u.i];
        if (line === undefined)
            continue;
        const approx = /^\s*[~≈]/.test(line);
        const base = line.replace(/^\s*[~≈]\s*/, '').replace(/^\s*(?:for\s+(?:the\s+)?)?[a-z][a-z ]{1,24}?\s*:\s+(?=\S)/i, (m) => (/\d/.test(m) ? m : ''));
        const item = ingredientToItem(scaleIngredient(base, factor));
        // keep her casing ("butter", "Yukon Gold potatoes"): find the name in the line
        const at = base.toLowerCase().indexOf(item.text.toLowerCase());
        const name = at >= 0 ? base.slice(at, at + item.text.length) : item.text;
        let qty = u.amount ? scaleIngredient(amountWithoutName(u.amount, name), factor) : item.qty;
        if (qty && approx && !u.amount)
            qty = `~${qty}`;
        out.push({ i: u.i, qty: qty || null, name, partial: !!u.amount, shared: !!u.shared });
    }
    return out;
}
/** "4 carrots" / "1 onion" for the line "4 carrots" / "1 yellow onion": the name is shown next to it, keep "4" / "1". */
function amountWithoutName(amount, name) {
    const nameWords = new Set(words(name).map((x) => x.w));
    const parts = amount.trim().split(/\s+/);
    while (parts.length > 1 && nameWords.has(keyOf(parts[parts.length - 1])))
        parts.pop();
    return parts.join(' ');
}
/** "2 tbsp butter" (for speech and plain text). */
export const stepIngText = (l) => (l.qty ? `${l.qty} ${l.name}` : l.name);
