// GENERATED by tools/build.mjs from emm-blog-app/src/features/recipes/stepIngTypes.ts. Do not edit.
// Shared contract for POST /api/recipe-step-ingredients ("which ingredients, and how much, does each step use?")
// + the pure helpers for the mapping stored on steps. Used by the API route, the app and the website.
// Pure TS only: no React Native or server imports (see ARCHITECTURE.md ## Recipes → Ingredients per step).
export const STEP_INGS_LIMITS = { ingredients: 80, ingredient: 500, steps: 60, step: 2000, body: 120000, perStep: 30, amount: 40 };
const CTRL = /[\u0000-\u001F\u007F‪-‮⁦-⁩]/g;
/**
 * Validate a mapping (from the server, the model or storage): exactly `nSteps` lists, each with unique
 * in-range ingredient indexes, amounts trimmed/bounded (empty = whole line). Junk becomes empty lists.
 */
export function sanitizeStepIngs(raw, nIngs, nSteps) {
    const out = [];
    const arr = Array.isArray(raw) ? raw : [];
    for (let s = 0; s < nSteps; s++) {
        const list = Array.isArray(arr[s]) ? arr[s] : [];
        const seen = new Set();
        const uses = [];
        for (const u of list) {
            if (!u || typeof u !== 'object')
                continue;
            const i = u.i;
            if (typeof i !== 'number' || !Number.isInteger(i) || i < 0 || i >= nIngs || seen.has(i))
                continue;
            seen.add(i);
            const a = u.amount;
            const amount = typeof a === 'string' ? a.replace(CTRL, '').replace(/\s+/g, ' ').trim().slice(0, STEP_INGS_LIMITS.amount) : '';
            uses.push(amount ? { i, amount } : { i });
            if (uses.length >= STEP_INGS_LIMITS.perStep)
                break;
        }
        out.push(uses);
    }
    return out;
}
/** Short signature of the recipe's ingredient + step texts: a stored mapping is only valid for the texts it was made for. */
export function stepIngsSig(ingredients, steps) {
    const s = `${ingredients.map((x) => x.trim()).join('\n')}\u0001${steps.map((x) => x.trim()).join('\n')}`;
    let h = 0x811c9dc5;
    for (let k = 0; k < s.length; k++) {
        h ^= s.charCodeAt(k);
        h = Math.imul(h, 0x01000193) >>> 0;
    }
    return `${s.length.toString(36)}.${h.toString(36)}`;
}
/** The stored AI mapping when it still matches the recipe's texts, else null. */
export function storedStepIngs(ingredients, steps) {
    if (!steps.length)
        return null;
    const sig = stepIngsSig(ingredients.map((i) => i.text), steps.map((s) => s.text));
    if (!steps.every((s) => s.ingsSig === sig && Array.isArray(s.ings)))
        return null;
    return sanitizeStepIngs(steps.map((s) => s.ings), ingredients.length, steps.length);
}
