// GENERATED by tools/build.mjs from emm-blog-app/src/features/recipes/tags.ts. Do not edit.
import { KNOWN_EMOJIS, KNOWN_TAGS } from './importTypes.js';
export const DEFAULT_TAGS = KNOWN_TAGS;
const TAG_EMOJI = {
    breakfast: '🥞',
    lunch: '🥪',
    dinner: '🍝',
    dessert: '🍰',
    snack: '🍿',
    drinks: '🧋',
    baking: '🧁',
    healthy: '🥗',
    'date night': '🕯️',
    comfort: '🧸',
    quick: '⚡',
};
export const tagLabel = (t) => `${TAG_EMOJI[t] ?? '🏷️'} ${t}`;
export const FOOD_EMOJIS = KNOWN_EMOJIS;
