// GENERATED by tools/build.mjs from emm-blog-app/src/features/today/events.ts. Do not edit.
// ---------------------------------------------------------------------------
// Calendar events (pure, node-testable; also compiled into the website).
// Events happen at a time and are never ticked off ("Dinner with Mom", "Dentist"). They reuse the task
// repeat rules (recurrence.ts) with `date` as the anchor. Stored in the `events` table (migration v5).
// ---------------------------------------------------------------------------
import { addDays, describeDate, formatTimeRange, occursOn } from './recurrence.js';
import { normalizeReminders } from './reminders.js';
export const EVENT_COLORS = 6;
const asRule = (e) => ({ dueDate: e.date, repeat: e.repeat, createdAt: e.createdAt });
export const eventOccursOn = (e, date) => occursOn(asRule(e), date);
/** All-day first, then by start time, then title. */
export const byEventTime = (a, b) => {
    const ta = a.allDay || !a.start ? '' : a.start;
    const tb = b.allDay || !b.start ? '' : b.start;
    if (ta !== tb)
        return ta < tb ? -1 : 1;
    return a.title.localeCompare(b.title) || a.createdAt - b.createdAt;
};
/** What happens on `date`, in the order the "Happening" section shows it. */
export function eventsOn(events, date) {
    return events
        .filter((e) => eventOccursOn(e, date))
        .sort(byEventTime)
        .map((event) => ({ key: `${event.id}@${date}`, event, date }));
}
/** Every occurrence in `from`..`to` (inclusive), by date then time. */
export function eventOccurrences(events, from, to) {
    const out = [];
    for (let d = from; d <= to; d = addDays(d, 1))
        out.push(...eventsOn(events, d));
    return out;
}
/** Per-day number of events in `from`..`to` (days with none are left out). */
export function eventCountsForRange(events, from, to) {
    const out = new Map();
    if (!events.length || to < from)
        return out;
    for (let d = from; d <= to; d = addDays(d, 1)) {
        let n = 0;
        for (const e of events)
            if (d >= e.date && eventOccursOn(e, d))
                n++;
        if (n)
            out.set(d, n);
    }
    return out;
}
/** "All day", "7:00 PM", "7:00 – 8:30 PM" */
export function describeEventTime(e) {
    if (e.allDay || !e.start)
        return 'All day';
    return formatTimeRange(e.start, e.end);
}
/** Title with the optional emoji in front. */
export const eventTitle = (e) => (e.emoji ? `${e.emoji} ${e.title}` : e.title);
/** A new event with defaults filled in (no write). */
export function makeEvent(v, now = Date.now(), id = '') {
    const allDay = !v.start || (v.allDay ?? false);
    return {
        id,
        title: v.title.trim(),
        emoji: v.emoji || null,
        date: v.date,
        allDay,
        start: allDay ? null : (v.start ?? null),
        end: allDay ? null : (v.end ?? null),
        location: (v.location ?? '').trim(),
        notes: v.notes ?? '',
        repeat: v.repeat ?? null,
        color: Math.max(0, Math.min(EVENT_COLORS - 1, Math.floor(v.color ?? 0))) || 0,
        reminders: normalizeReminders(v.reminders ?? []),
        createdAt: v.createdAt ?? now,
        updatedAt: v.updatedAt ?? now,
    };
}
/** `end` = `start` + minutes (clamped to 23:55 the same day). */
export function addMinutes(hhmm, mins) {
    const [h, m] = hhmm.split(':').map((x) => parseInt(x, 10));
    const t = Math.min(23 * 60 + 55, Math.max(0, (h || 0) * 60 + (m || 0) + mins));
    return `${String(Math.floor(t / 60)).padStart(2, '0')}:${String(t % 60).padStart(2, '0')}`;
}
// ---------- "is this an event?" (quick add suggestion; tasks stay the default) ----------
const EVENT_WORDS = /\b(dinner|lunch|brunch|breakfast|coffee|drinks|date night|date|party|birthday|bday|anniversary|wedding|shower|concert|show|movie|movies|game|match|recital|dentist|doctor|dr\.?|appointment|appt|checkup|check-up|vet|haircut|hair|nails|massage|spa|therapy|meeting|interview|call with|zoom|class|lesson|practice|rehearsal|flight|trip|vacation|holiday|visit|reservation|festival|church|service|brunch)\b/i;
/**
 * Does a quick-add line read like an event ("dinner with mom fri 7pm", "dentist tue 3pm")? Only a hint: the add
 * sheet offers "Make it an event" and tasks stay the default. Needs a day or a time plus an event-ish word
 * (or "with <someone>").
 */
export function looksLikeEvent(text, parsed) {
    if (!parsed.date && !parsed.time)
        return false;
    const t = text.toLowerCase();
    if (/\b(pay|buy|call|email|text|clean|wash|vacuum|laundry|order|book|schedule|renew|return|pick up|cancel)\b/.test(t) && !/\bwith\b/.test(t))
        return false;
    return EVENT_WORDS.test(t) || /\bwith\s+[a-z]/i.test(t);
}
/**
 * The month view's "Upcoming" list: events (every occurrence) + dated, not-done tasks in `today`..`today+days-1`.
 * To stay calm it leaves out routine chores and tasks that repeat daily/weekly (they'd flood it); monthly/yearly
 * ones ("Pay rent") are in. `isDone(taskId, doneKey)` hides ticked ones. At most `limit` rows.
 */
export function upcomingItems(events, tasks, today, opts = {}) {
    const days = opts.days ?? 14;
    const to = addDays(today, days - 1);
    const out = [];
    for (const o of eventOccurrences(events, today, to)) {
        const e = o.event;
        out.push({ key: `e-${o.key}`, kind: 'event', id: e.id, date: o.date, time: e.allDay ? null : e.start, title: eventTitle(e), day: describeDate(o.date, today), color: e.color });
    }
    for (const t of tasks) {
        if (t.archived || t.routineId)
            continue;
        const title = t.emoji ? `${t.emoji} ${t.title}` : t.title;
        if (!t.repeat) {
            if (!t.dueDate || t.dueDate < today || t.dueDate > to || opts.isDone?.(t.id, 'once'))
                continue;
            out.push({ key: `t-${t.id}@${t.dueDate}`, kind: 'task', id: t.id, date: t.dueDate, time: t.dueTime, title, day: describeDate(t.dueDate, today), color: -1 });
            continue;
        }
        if (t.repeat.k !== 'monthly' && t.repeat.k !== 'yearly')
            continue;
        for (let d = today; d <= to; d = addDays(d, 1)) {
            if (!occursOn(t, d) || opts.isDone?.(t.id, d))
                continue;
            out.push({ key: `t-${t.id}@${d}`, kind: 'task', id: t.id, date: d, time: t.dueTime, title, day: describeDate(d, today), color: -1 });
        }
    }
    // by day, then untimed/all-day first, then time; events before tasks at the same time
    const cmp = (x, y) => (x < y ? -1 : x > y ? 1 : 0);
    out.sort((a, b) => cmp(a.date, b.date) || cmp(a.time ?? '', b.time ?? '') || (a.kind === b.kind ? 0 : a.kind === 'event' ? -1 : 1));
    return out.slice(0, opts.limit ?? 20);
}
