// GENERATED by tools/build.mjs from emm-blog-app/src/features/today/parseTask.ts. Do not edit.
// ---------------------------------------------------------------------------
// Quick-add natural language for tasks (pure, node-testable).
//   "dentist fri 3pm"              → Dentist · Fri · 15:00
//   "clean bathroom every other saturday" → weekly {days:[6], every:2}
//   "pay rent monthly on the 1st"  → monthly {day:1}
// The matched words are removed from the title. Nothing understood → just a title.
// ---------------------------------------------------------------------------
import { addDays, daysInMonth, dow, firstOnOrAfter, fromKey, toKey } from './recurrence.js';
const DAY = '(sun(?:day)?|mon(?:day)?|tue(?:s(?:day)?)?|wed(?:s|nesday)?|thu(?:r(?:s(?:day)?)?)?|fri(?:day)?|sat(?:urday)?)';
const DAYS_PLURAL = '(sundays|mondays|tuesdays|wednesdays|thursdays|fridays|saturdays)';
const SEP = '(?:\\s*,\\s*(?:and\\s+)?|\\s+and\\s+|\\s*&\\s*|\\s*\\/\\s*|\\s+)';
const DAY_LIST = `${DAY}s?(?:${SEP}${DAY}s?)*`;
const MONTH = '(jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|june?|july?|aug(?:ust)?|sep(?:t(?:ember)?)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)';
const ORD = '(\\d{1,2})(?:st|nd|rd|th)';
const NUM_WORDS = { a: 1, an: 1, one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9, ten: 10, other: 2 };
const dayIndex = (w) => ['su', 'mo', 'tu', 'we', 'th', 'fr', 'sa'].indexOf(w.toLowerCase().slice(0, 2));
const monthIndex = (w) => ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'].indexOf(w.toLowerCase().slice(0, 3));
const num = (w) => (/^\d+$/.test(w) ? parseInt(w, 10) : (NUM_WORDS[w.toLowerCase()] ?? NaN));
const daysIn = (text) => {
    const out = [];
    const re = new RegExp(DAY, 'gi');
    let m;
    while ((m = re.exec(text))) {
        const d = dayIndex(m[1]);
        if (d >= 0 && !out.includes(d))
            out.push(d);
    }
    return out;
};
const hhmm = (h, m) => `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`;
/** A calendar date for month/day: this year, or next year if it already passed (unless `year` given). */
function monthDay(today, m0, d, year) {
    const t = fromKey(today);
    let y = year ?? t.getFullYear();
    if (year !== undefined && year < 100)
        y = 2000 + year;
    if (m0 < 0 || m0 > 11 || d < 1 || d > daysInMonth(y, m0 + 1))
        return null;
    let key = toKey(new Date(y, m0, d));
    if (year === undefined && key < today)
        key = toKey(new Date(y + 1, m0, Math.min(d, daysInMonth(y + 1, m0 + 1))));
    return key;
}
/** The next date (on/after today) with that day of the month (skips months that are too short). */
function nextDayOfMonth(today, d) {
    if (d < 1 || d > 31)
        return null;
    const t = fromKey(today);
    for (let i = 0; i < 13; i++) {
        const y = t.getFullYear() + Math.floor((t.getMonth() + i) / 12);
        const m0 = (t.getMonth() + i) % 12;
        if (d > daysInMonth(y, m0 + 1))
            continue;
        const key = toKey(new Date(y, m0, d));
        if (key >= today)
            return key;
    }
    return null;
}
/** First `day` (0-6) on/after `from` (strict = after). */
function nextDow(from, day, strict = false) {
    let n = (day - dow(from) + 7) % 7;
    if (strict && n === 0)
        n = 7;
    return addDays(from, n);
}
/** Parse a quick-add line. `today` = local 'yyyy-mm-dd'. */
export function parseTask(input, today) {
    let s = ` ${input.replace(/\s+/g, ' ').trim()} `;
    let date = null;
    let time = null;
    let repeat = null;
    let anytime = false;
    // weekly/monthly/yearly rules that still need their day from elsewhere in the text
    let needDays = false;
    let needMonthDay = false;
    let monthDayFromStart = false;
    /** Find `re` (case-insensitive) and remove it if `fn` accepts the match (returns anything but false). */
    const take = (re, fn) => {
        const rx = new RegExp(re, 'i');
        const m = rx.exec(s);
        if (!m)
            return false;
        if (fn(m) === false)
            return false;
        s = `${s.slice(0, m.index)} ${s.slice(m.index + m[0].length)}`;
        return true;
    };
    const B = '(?<![\\w/:])'; // word start (no letters, digits, slashes or colons before)
    const E = '(?![\\w/:])'; // word end
    // ---- repeats ----
    take(`${B}(?:every|each)\\s+other\\s+day${E}`, () => void (repeat = { k: 'daily', every: 2 })) ||
        take(`${B}(?:every|each)\\s+(\\d+|two|three|four|five|six|seven|ten)\\s+days?${E}`, (m) => {
            const n = num(m[1]);
            if (!(n >= 1 && n <= 365))
                return false;
            repeat = { k: 'daily', every: n };
        }) ||
        take(`${B}(?:every|each)\\s+(\\d+|other|two|three|four)\\s+weeks?(?:\\s+on)?${E}`, (m) => {
            repeat = { k: 'weekly', days: [], every: Math.max(1, num(m[1]) || 1) };
            needDays = true;
        }) ||
        take(`${B}(?:every|each)\\s+other\\s+(${DAY_LIST})${E}`, (m) => void (repeat = { k: 'weekly', days: daysIn(m[1]), every: 2 })) ||
        take(`${B}(?:every|each)\\s+(\\d+|other|two|three|four|six)\\s+months?(?:\\s+on)?${E}`, (m) => {
            repeat = { k: 'monthly', day: 1, every: Math.max(1, num(m[1]) || 1) };
            needMonthDay = true;
        }) ||
        take(`${B}(?:(?:every|each|on)\\s+)?(?:week\\s?days?|weekdays)${E}`, (m) => {
            // "weekday" alone is too vague; "every weekday" / "weekdays" / "on weekdays"
            if (!/every|each|days/i.test(m[0]))
                return false;
            repeat = { k: 'weekly', days: [1, 2, 3, 4, 5] };
        }) ||
        take(`${B}(?:(?:every|each)\\s+weekend|(?:on\\s+)?weekends)${E}`, () => void (repeat = { k: 'weekly', days: [0, 6] })) ||
        take(`${B}(?:every|each)\\s+(${DAY_LIST})${E}`, (m) => void (repeat = { k: 'weekly', days: daysIn(m[1]) })) ||
        take(`${B}(?:on\\s+)?${DAYS_PLURAL}${E}`, (m) => void (repeat = { k: 'weekly', days: daysIn(m[1]) })) ||
        take(`${B}(?:every\\s*day|each\\s+day|daily|every\\s+(?:morning|night|evening))${E}`, () => void (repeat = { k: 'daily' })) ||
        take(`${B}(?:biweekly|fortnightly|every\\s+other\\s+week)(?:\\s+on)?${E}`, () => {
            repeat = { k: 'weekly', days: [], every: 2 };
            needDays = true;
        }) ||
        take(`${B}(?:(?:every|each)\\s+week|weekly)(?:\\s+on)?${E}`, () => {
            repeat = { k: 'weekly', days: [] };
            needDays = true;
        }) ||
        take(`${B}(?:every|each)\\s+(?:month\\s+on\\s+)?(?:the\\s+)?${ORD}(?:\\s+of\\s+(?:the|every)\\s+month)?${E}`, (m) => {
            repeat = { k: 'monthly', day: parseInt(m[1], 10) };
        }) ||
        take(`${B}(?:(?:every|each)\\s+month|monthly)(?:\\s+on)?${E}`, () => {
            repeat = { k: 'monthly', day: 1 };
            needMonthDay = true;
        }) ||
        take(`${B}(?:(?:every|each)\\s+year|yearly|annually)(?:\\s+on)?${E}`, () => {
            repeat = { k: 'yearly', month: 1, day: 1 };
        });
    // a rule that still needs its day(s): "weekly on friday", "monthly on the 1st"
    const r0 = repeat;
    if (needDays && r0?.k === 'weekly') {
        take(`${B}(?:on\\s+)?(${DAY_LIST})${E}`, (m) => void (r0.days = daysIn(m[1])));
    }
    if (needMonthDay && r0?.k === 'monthly') {
        let found = take(`${B}(?:on\\s+)?(?:the\\s+)?${ORD}${E}`, (m) => {
            const d = parseInt(m[1], 10);
            if (d < 1 || d > 31)
                return false;
            r0.day = d;
        });
        if (!found)
            found = take(`${B}on\\s+(?:the\\s+)?(\\d{1,2})${E}`, (m) => {
                const d = parseInt(m[1], 10);
                if (d < 1 || d > 31)
                    return false;
                r0.day = d;
            });
        if (!found)
            monthDayFromStart = true;
    }
    // ---- time ----
    take(`${B}(?:at\\s+|@\\s*)?(\\d{1,2})(?::(\\d{2}))?\\s*(am|pm|a\\.m\\.|p\\.m\\.)(?![\\w])`, (m) => {
        let h = parseInt(m[1], 10);
        const min = m[2] ? parseInt(m[2], 10) : 0;
        if (h < 1 || h > 12 || min > 59)
            return false;
        const pm = m[3].toLowerCase().startsWith('p');
        if (h === 12)
            h = pm ? 12 : 0;
        else if (pm)
            h += 12;
        time = hhmm(h, min);
    }) ||
        take(`${B}(?:at\\s+|@\\s*)?(\\d{1,2}):(\\d{2})${E}`, (m) => {
            const h = parseInt(m[1], 10);
            const min = parseInt(m[2], 10);
            if (h > 23 || min > 59)
                return false;
            // "at 3:30" with no am/pm: 1-6 are afternoon (nobody plans 3:30am)
            time = hhmm(h >= 1 && h <= 6 ? h + 12 : h, min);
        }) ||
        take(`${B}(?:at\\s+)?noon${E}`, () => void (time = '12:00')) ||
        take(`${B}(?:at|@)\\s*(\\d{1,2})${E}`, (m) => {
            const h = parseInt(m[1], 10);
            if (h > 23)
                return false;
            time = hhmm(h >= 1 && h <= 6 ? h + 12 : h, 0);
        });
    // ---- dates ----
    take(`${B}(anytime|any time|someday|whenever)${E}`, () => void (anytime = true));
    let explicitDate = null;
    const setDate = (d) => {
        if (!d)
            return false;
        explicitDate = d;
    };
    take(`${B}(?:the\\s+)?day\\s+after\\s+tomorrow${E}`, () => setDate(addDays(today, 2))) ||
        take(`${B}(?:tomorrow|tmrw|tmr|tomorow|tommorow)${E}`, () => setDate(addDays(today, 1))) ||
        take(`${B}(?:today|tonight|tonite|this\\s+(?:morning|afternoon|evening))${E}`, () => setDate(today)) ||
        take(`${B}in\\s+(\\d+|a|an|one|two|three|four|five|six|seven|ten)\\s+(days?|weeks?|months?)${E}`, (m) => {
            const n = num(m[1]);
            if (!(n >= 0))
                return false;
            const unit = m[2].toLowerCase();
            if (unit.startsWith('day'))
                return setDate(addDays(today, n));
            if (unit.startsWith('week'))
                return setDate(addDays(today, n * 7));
            const t = fromKey(today);
            const y = t.getFullYear() + Math.floor((t.getMonth() + n) / 12);
            const m0 = (t.getMonth() + n) % 12;
            return setDate(toKey(new Date(y, m0, Math.min(t.getDate(), daysInMonth(y, m0 + 1)))));
        }) ||
        take(`${B}next\\s+week${E}`, () => setDate(nextDow(today, 1, true))) ||
        take(`${B}(?:this\\s+|next\\s+)?weekend${E}`, (m) => {
            const d = dow(today);
            if (/next/i.test(m[0]))
                return setDate(nextDow(addDays(today, 1), 6, true));
            return setDate(d === 6 || d === 0 ? today : nextDow(today, 6));
        }) ||
        take(`${B}next\\s+${DAY}${E}`, (m) => setDate(nextDow(today, dayIndex(m[1]), true))) ||
        take(`${B}(?:on\\s+|this\\s+)?${MONTH}\\.?\\s+(\\d{1,2})(?:st|nd|rd|th)?(?:,?\\s+(\\d{4}))?${E}`, (m) => setDate(monthDay(today, monthIndex(m[1]), parseInt(m[2], 10), m[3] ? parseInt(m[3], 10) : undefined))) ||
        take(`${B}(?:on\\s+)?(?:the\\s+)?(\\d{1,2})(?:st|nd|rd|th)?\\s+(?:of\\s+)?${MONTH}(?:,?\\s+(\\d{4}))?${E}`, (m) => setDate(monthDay(today, monthIndex(m[2]), parseInt(m[1], 10), m[3] ? parseInt(m[3], 10) : undefined))) ||
        take(`${B}(?:on\\s+)?(\\d{1,2})\\/(\\d{1,2})(?:\\/(\\d{2}|\\d{4}))?${E}`, (m) => setDate(monthDay(today, parseInt(m[1], 10) - 1, parseInt(m[2], 10), m[3] ? parseInt(m[3], 10) : undefined))) ||
        take(`${B}(?:on\\s+)?the\\s+${ORD}${E}`, (m) => setDate(nextDayOfMonth(today, parseInt(m[1], 10)))) ||
        take(`${B}on\\s+(?:the\\s+)?${ORD}${E}`, (m) => setDate(nextDayOfMonth(today, parseInt(m[1], 10)))) ||
        take(`${B}(?:on\\s+|this\\s+)?${DAY}${E}`, (m) => setDate(nextDow(today, dayIndex(m[1]))));
    // ---- settle repeats ----
    const r = repeat;
    const start = explicitDate;
    if (r) {
        if (r.k === 'weekly' && !r.days.length)
            r.days = [dow(start ?? today)];
        if (r.k === 'yearly') {
            const src = fromKey(start ?? today);
            r.month = src.getMonth() + 1;
            r.day = src.getDate();
        }
        if (r.k === 'monthly' && monthDayFromStart)
            r.day = fromKey(start ?? today).getDate();
        date = start ?? firstOnOrAfter(r, today);
        // a weekly start that isn't one of its days: move it to the first real one
        if (start && r.k === 'weekly' && !r.days.includes(dow(start)))
            date = firstOnOrAfter(r, start);
        anytime = false;
    }
    else {
        date = start;
        if (anytime)
            date = null;
    }
    const title = cleanTitle(s);
    const understood = !!(repeat || date || time || anytime);
    return { title, date, time, repeat, anytime, understood };
}
/** Tidy what's left once the date words are gone: spaces, dangling "on/at/by", first letter capital. */
function cleanTitle(s) {
    let t = s.replace(/\s+/g, ' ').trim();
    t = t.replace(/(?:[\s,;·\-–—]+|\s+(?:on|at|by|every|each|in|for|and|from|starting|the|@))+$/i, '').trim();
    t = t.replace(/^(?:(?:on|at|by|every|each)\s+|[,;·\-–—]\s*)+/i, '').trim();
    t = t.replace(/(?:[\s,;·\-–—]+|\s+(?:on|at|by|every|each|in|for|and|from|starting|the|@))+$/i, '').trim();
    if (t && /[a-z]/.test(t[0]))
        t = t[0].toUpperCase() + t.slice(1);
    return t;
}
