// GENERATED by tools/build.mjs from emm-blog-app/src/features/today/recurrence.ts. Do not edit.
// ---------------------------------------------------------------------------
// Pure planner logic for the Today tab: local-date helpers, repeat rules, and
// the day plan builder. NO React Native / expo imports (node-testable).
// Dates are local 'yyyy-mm-dd' keys; all math goes through local Date objects
// at midnight and rounds day differences, so DST changes never shift a day.
// ---------------------------------------------------------------------------
/** The `task_done.date` key for one-off tasks (so moving a done task's date never loses the tick). */
export const ONCE = 'once';
// ---------- local date helpers ----------
const pad = (n) => String(n).padStart(2, '0');
export const toKey = (d) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
export function fromKey(key) {
    const [y, m, d] = key.split('-').map((x) => parseInt(x, 10));
    return new Date(y || 2000, (m || 1) - 1, d || 1);
}
export const todayKey = (now = new Date()) => toKey(now);
export function addDays(key, n) {
    const d = fromKey(key);
    d.setDate(d.getDate() + n);
    return toKey(d);
}
/** Whole days from a to b (b later = positive). DST-safe. */
export const daysBetween = (a, b) => Math.round((fromKey(b).getTime() - fromKey(a).getTime()) / 86400000);
/** 0 = Sunday … 6 = Saturday */
export const dow = (key) => fromKey(key).getDay();
export const daysInMonth = (y, m1) => new Date(y, m1, 0).getDate();
/** Monday of the key's week. */
export const weekStart = (key) => addDays(key, -((dow(key) + 6) % 7));
/** The local date a timestamp falls on. */
export const keyOfTime = (ms) => toKey(new Date(ms));
export const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
export const DAY_SHORT = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
export const MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
export const MONTH_SHORT = MONTH_NAMES.map((m) => m.slice(0, 3));
export function ordinal(n) {
    const s = ['th', 'st', 'nd', 'rd'];
    const v = n % 100;
    return n + (s[(v - 20) % 10] || s[v] || s[0]);
}
// ---------- repeat rules ----------
const anchorOf = (t) => t.dueDate ?? keyOfTime(t.createdAt || 0);
/** Does the task happen on `date`? One-off: its due date. Repeating: the rule, on/after its start. */
export function occursOn(t, date) {
    const r = t.repeat;
    if (!r)
        return t.dueDate === date;
    const anchor = anchorOf(t);
    if (date < anchor)
        return false;
    const every = Math.max(1, Math.floor(('every' in r && r.every) || 1));
    switch (r.k) {
        case 'daily':
            return daysBetween(anchor, date) % every === 0;
        case 'weekly': {
            if (!r.days.includes(dow(date)))
                return false;
            if (every === 1)
                return true;
            const weeks = Math.round(daysBetween(weekStart(anchor), weekStart(date)) / 7);
            return weeks % every === 0;
        }
        case 'monthly': {
            const d = fromKey(date);
            const y = d.getFullYear();
            const m = d.getMonth() + 1;
            if (d.getDate() !== Math.min(r.day, daysInMonth(y, m)))
                return false;
            if (every === 1)
                return true;
            const a = fromKey(anchor);
            const months = (y - a.getFullYear()) * 12 + (m - 1 - a.getMonth());
            return months % every === 0;
        }
        case 'yearly': {
            const d = fromKey(date);
            const y = d.getFullYear();
            return d.getMonth() + 1 === r.month && d.getDate() === Math.min(r.day, daysInMonth(y, r.month));
        }
    }
}
/** The first date strictly after `after` the task happens on (null if never). */
export function nextOccurrence(t, after) {
    if (!t.repeat)
        return t.dueDate && t.dueDate > after ? t.dueDate : null;
    let d = addDays(after, 1);
    const anchor = anchorOf(t);
    if (d < anchor)
        d = anchor;
    // yearly / every-N-months rules can be up to a few years apart; a local loop is still < 1ms
    for (let i = 0; i < 366 * 4 + 1; i++) {
        if (occursOn(t, d))
            return d;
        d = addDays(d, 1);
    }
    return null;
}
/** First date on/after `from` the rule happens (used to pick a sensible start for a new rule). */
export function firstOnOrAfter(repeat, from) {
    const probe = { dueDate: from, repeat: repeat.k === 'daily' ? { k: 'daily' } : repeat, createdAt: 0 };
    return occursOn(probe, from) ? from : (nextOccurrence(probe, from) ?? from);
}
// ---------- labels ----------
/** "3:00 PM" */
export function formatTime(hhmm) {
    if (!hhmm)
        return '';
    const [h, m] = hhmm.split(':').map((x) => parseInt(x, 10));
    const hr = ((h + 11) % 12) + 1;
    return `${hr}:${pad(m || 0)} ${h >= 12 ? 'PM' : 'AM'}`;
}
const listDays = (days, long) => {
    const names = [...days].sort((a, b) => ((a + 6) % 7) - ((b + 6) % 7)).map((d) => (long ? DAY_NAMES[d] : DAY_SHORT[d]));
    return names.length <= 2 ? names.join(' & ') : `${names.slice(0, -1).join(', ')} & ${names[names.length - 1]}`;
};
/** "Every day", "Every 3 days", "Weekdays", "Every Monday", "Every other Saturday", "Monthly on the 1st", "Yearly on Sep 30" */
export function describeRepeat(r) {
    const every = Math.max(1, ('every' in r && r.every) || 1);
    switch (r.k) {
        case 'daily':
            return every === 1 ? 'Every day' : every === 2 ? 'Every other day' : `Every ${every} days`;
        case 'weekly': {
            const days = [...new Set(r.days)];
            const set = days.slice().sort().join('');
            let what = set === '12345' ? 'Weekdays' : set === '06' ? 'Weekends' : days.length === 7 ? 'Every day' : '';
            if (every === 1)
                return what || `Every ${listDays(days, days.length === 1)}`;
            what = what ? what.toLowerCase() : listDays(days, days.length === 1);
            return every === 2 ? `Every other ${what}` : `Every ${every} weeks on ${what}`;
        }
        case 'monthly':
            return every === 1 ? `Monthly on the ${ordinal(r.day)}` : `Every ${every} months on the ${ordinal(r.day)}`;
        case 'yearly':
            return `Yearly on ${MONTH_SHORT[r.month - 1]} ${r.day}`;
    }
}
/** "Today", "Tomorrow", "Yesterday", "Fri" (within the next 6 days), "Sep 30", "Sep 30, 2027" */
export function describeDate(date, today) {
    const n = daysBetween(today, date);
    if (n === 0)
        return 'Today';
    if (n === 1)
        return 'Tomorrow';
    if (n === -1)
        return 'Yesterday';
    const d = fromKey(date);
    if (n > 1 && n < 7)
        return DAY_SHORT[d.getDay()];
    const md = `${MONTH_SHORT[d.getMonth()]} ${d.getDate()}`;
    return d.getFullYear() === fromKey(today).getFullYear() ? md : `${md}, ${d.getFullYear()}`;
}
/** What the preview chip / meta line says: "Every Monday", "Fri · 3:00 PM", "Anytime". */
export function describeWhen(w, today) {
    const head = w.repeat ? describeRepeat(w.repeat) : w.date ? describeDate(w.date, today) : 'Anytime';
    return w.time ? `${head} · ${formatTime(w.time)}` : head;
}
/** "Thursday, Sep 25" */
export function longDate(key) {
    const d = fromKey(key);
    return `${DAY_NAMES[d.getDay()]}, ${MONTH_SHORT[d.getMonth()]} ${d.getDate()}`;
}
const byTimeThenSort = (a, b) => {
    const ta = a.task.dueTime ?? '99:99';
    const tb = b.task.dueTime ?? '99:99';
    if (ta !== tb)
        return ta < tb ? -1 : 1;
    return a.task.sort - b.task.sort || a.task.createdAt - b.task.createdAt;
};
/** Index done marks once; pass the result to buildDayPlan for several days. */
export function indexDone(done) {
    const m = new Map();
    for (const d of done)
        m.set(`${d.taskId}|${d.date}`, d);
    return m;
}
/** The label a routine gives a day ("Floors" for Thursday cleaning), or null. */
export function routineDayLabel(r, date) {
    if (r.config.mode !== 'weekly')
        return null;
    return r.config.labels?.[String(dow(date))]?.trim() || null;
}
/**
 * Everything planned for `date` (pure). Overdue one-off tasks and anytime tasks only show on `today`;
 * a repeating task never piles up (only the viewed day's occurrence exists). Skipped occurrences
 * (snoozed repeating tasks) are hidden.
 */
export function buildDayPlan(input, date, today, doneIdx = indexDone(input.done)) {
    const isToday = date === today;
    const routines = new Map(input.routines.filter((r) => r.enabled).map((r) => [r.id, r]));
    const plan = { date, isToday, overdue: [], scheduled: [], routines: [], anytime: [], done: [], total: 0, doneCount: 0 };
    const groups = new Map();
    for (const t of input.tasks) {
        if (t.archived)
            continue;
        if (t.routineId && !routines.has(t.routineId))
            continue; // routine turned off
        let occ = null;
        if (t.repeat) {
            if (!occursOn(t, date))
                continue;
            const mark = doneIdx.get(`${t.id}|${date}`);
            if (mark?.skipped)
                continue;
            occ = { key: `${t.id}@${date}`, task: t, date, doneKey: date, done: !!mark, doneAt: mark?.doneAt ?? null, overdue: false };
        }
        else {
            const mark = doneIdx.get(`${t.id}|${ONCE}`);
            const doneToday = !!mark && keyOfTime(mark.doneAt) === date;
            if (t.dueDate === date) {
                occ = { key: `${t.id}@${date}`, task: t, date, doneKey: ONCE, done: !!mark, doneAt: mark?.doneAt ?? null, overdue: false };
            }
            else if (isToday && t.dueDate && t.dueDate < today && (!mark || doneToday)) {
                occ = { key: `${t.id}@${t.dueDate}`, task: t, date: t.dueDate, doneKey: ONCE, done: !!mark, doneAt: mark?.doneAt ?? null, overdue: !mark };
            }
            else if (isToday && !t.dueDate && (!mark || doneToday)) {
                if (!mark) {
                    plan.anytime.push({ key: `${t.id}@any`, task: t, date, doneKey: ONCE, done: false, doneAt: null, overdue: false });
                    continue;
                }
                occ = { key: `${t.id}@any`, task: t, date, doneKey: ONCE, done: true, doneAt: mark.doneAt, overdue: false };
            }
        }
        if (!occ)
            continue;
        if (occ.done)
            plan.done.push(occ);
        else if (occ.overdue)
            plan.overdue.push(occ);
        else if (t.routineId) {
            const g = groups.get(t.routineId) ?? [];
            g.push(occ);
            groups.set(t.routineId, g);
        }
        else
            plan.scheduled.push(occ);
    }
    plan.overdue.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : byTimeThenSort(a, b)));
    plan.scheduled.sort(byTimeThenSort);
    plan.anytime.sort((a, b) => a.task.sort - b.task.sort || a.task.createdAt - b.task.createdAt);
    plan.done.sort((a, b) => (a.doneAt ?? 0) - (b.doneAt ?? 0));
    plan.routines = [...groups.entries()]
        .map(([id, items]) => ({ routine: routines.get(id), label: routineDayLabel(routines.get(id), date), items: items.sort(byTimeThenSort) }))
        .sort((a, b) => a.routine.sort - b.routine.sort || a.routine.createdAt - b.routine.createdAt);
    const routineCount = plan.routines.reduce((n, g) => n + g.items.length, 0);
    plan.total = plan.overdue.length + plan.scheduled.length + routineCount + plan.done.length;
    plan.doneCount = plan.done.length;
    return plan;
}
/** Open (not done) items in the order Home shows them: overdue, then timed, then the rest (incl. routine chores). */
export function upNext(plan) {
    const routineItems = plan.routines.flatMap((g) => g.items);
    const rest = [...plan.scheduled, ...routineItems].sort((a, b) => {
        const at = a.task.dueTime ? 0 : 1;
        const bt = b.task.dueTime ? 0 : 1;
        return at - bt || byTimeThenSort(a, b);
    });
    return [...plan.overdue, ...rest];
}
export function snapshotOf(plan, limit = 8) {
    const open = upNext(plan).map((o) => ({ id: o.task.id, title: displayTitle(o.task), time: o.task.dueTime, done: false, overdue: o.overdue }));
    const done = plan.done.map((o) => ({ id: o.task.id, title: displayTitle(o.task), time: o.task.dueTime, done: true, overdue: false }));
    return { date: plan.date, total: plan.total, done: plan.doneCount, items: [...open, ...done].slice(0, limit) };
}
/** Title with the optional emoji in front. */
export const displayTitle = (t) => (t.emoji ? `${t.emoji} ${t.title}` : t.title);
/**
 * Per-day counts for `from`..`to` (inclusive) in one pass, for the month calendar (≤ 42 days).
 * Matches `buildDayPlan(…).total/doneCount` for every day: repeating tasks count on each
 * occurrence (skipped = hidden, ticked per date), one-off tasks on their due date (ticked via
 * ONCE); on `today` also the open overdue one-offs and one-offs/anytime tasks ticked today.
 * `routines` (optional) hides chores of switched-off routines. Days with nothing are left out.
 */
export function countsForRange(tasks, done, from, to, opts = {}) {
    const out = new Map();
    if (to < from)
        return out;
    const idx = opts.doneIdx ?? indexDone(done);
    const enabled = opts.routines ? new Set(opts.routines.filter((r) => r.enabled).map((r) => r.id)) : null;
    const today = opts.today;
    const days = [];
    for (let d = from; d <= to; d = addDays(d, 1))
        days.push(d);
    const add = (date, isDone) => {
        const c = out.get(date) ?? { total: 0, done: 0 };
        c.total++;
        if (isDone)
            c.done++;
        out.set(date, c);
    };
    const todayIn = !!today && today >= from && today <= to;
    for (const t of tasks) {
        if (t.archived)
            continue;
        if (t.routineId && enabled && !enabled.has(t.routineId))
            continue;
        if (t.repeat) {
            const anchor = anchorOf(t);
            for (const d of days) {
                if (d < anchor || !occursOn(t, d))
                    continue;
                const mark = idx.get(`${t.id}|${d}`);
                if (mark?.skipped)
                    continue;
                add(d, !!mark);
            }
            continue;
        }
        const mark = idx.get(`${t.id}|${ONCE}`);
        if (t.dueDate && t.dueDate >= from && t.dueDate <= to)
            add(t.dueDate, !!mark);
        if (!todayIn || t.dueDate === today)
            continue;
        const doneToday = !!mark && keyOfTime(mark.doneAt) === today;
        // today also lists open overdue one-offs and anything (earlier / anytime) ticked today
        if (t.dueDate && t.dueDate < today && (!mark || doneToday))
            add(today, !!mark);
        else if (!t.dueDate && doneToday)
            add(today, true);
    }
    return out;
}
/** The 42 day keys (6 weeks, Sunday first) a month grid shows for `year`/`month0` (0-based month). */
export function monthGridDays(year, month0) {
    const first = new Date(year, month0, 1);
    const start = addDays(toKey(first), -first.getDay());
    return Array.from({ length: 42 }, (_, i) => addDays(start, i));
}
