// GENERATED by tools/build.mjs from emm-blog-app/src/features/today/reminders.ts. Do not edit.
// ---------------------------------------------------------------------------
// Reminders for tasks and events (pure, node-testable; also compiled into the website).
// Which local notifications should be pending right now: offsets → fire times, cute copy, repeat
// top-up under iOS's 64-pending limit (soonest first), and the diff against what's scheduled.
// The native glue (expo-notifications, the reminder_notifs table) lives in reminderSync.ts.
// ---------------------------------------------------------------------------
import { addDays, formatTime, formatTimeRange, fromKey, nextOccurrence, occursOn, toKey } from './recurrence.js';
/** At most this many reminders per item. */
export const MAX_REMINDERS = 2;
/** iOS keeps at most 64 pending local notifications per app; we leave a little room. */
export const PENDING_CAP = 60;
/** How far ahead repeating items are scheduled (yearly ones still get their next date). */
export const HORIZON_DAYS = 400;
export const MORNING = '09:00';
export const TIMED_OPTIONS = [
    { value: 0, label: 'At time' },
    { value: 5, label: '5 min' },
    { value: 15, label: '15 min' },
    { value: 30, label: '30 min' },
    { value: 60, label: '1 hr' },
    { value: 1440, label: '1 day' },
    { value: 'morning', label: 'Morning of' },
];
export const UNTIMED_OPTIONS = [
    { value: 'morning', label: 'Morning of' },
    { value: 1440, label: 'Day before' },
];
const ALLOWED = new Set([0, 5, 15, 30, 60, 1440, 'morning']);
/** Clean a stored/typed list: known values only, no duplicates, at most MAX_REMINDERS (the first ones kept). */
export function normalizeReminders(raw) {
    if (!Array.isArray(raw))
        return [];
    const out = [];
    for (const r of raw) {
        if (!ALLOWED.has(r) || out.includes(r))
            continue;
        out.push(r);
        if (out.length === MAX_REMINDERS)
            break;
    }
    return out;
}
/** What one tap on the bell picks: all-day / untimed items → the morning of, timed ones → 15 minutes before. */
export const defaultReminder = (timed) => (timed ? 15 : 'morning');
/** Toggle one option: off if on; else added (a third one replaces the oldest). */
export function toggleReminder(list, r) {
    if (list.includes(r))
        return list.filter((x) => x !== r);
    return [...list, r].slice(-MAX_REMINDERS);
}
/** Keep only what makes sense for untimed items (morning of / day before); minute offsets become the morning. */
export function fitReminders(list, timed) {
    if (timed)
        return list;
    return normalizeReminders(list.map((r) => (r === 1440 ? 1440 : 'morning')));
}
/** "30 min before", "Morning of (9 AM)", … for the meta line / a11y. */
export function reminderLabel(r, timed) {
    if (r === 'morning')
        return 'Morning of';
    if (!timed)
        return r === 1440 ? 'Day before' : 'Morning of';
    if (r === 0)
        return 'At time';
    if (r === 60)
        return '1 hr before';
    if (r === 1440)
        return '1 day before';
    return `${r} min before`;
}
export const describeReminders = (list, timed) => list.map((r) => reminderLabel(r, timed)).join(' + ');
// ---------- fire times ----------
const minutesOf = (hhmm) => {
    const [h, m] = hhmm.split(':').map((x) => parseInt(x, 10));
    return (h || 0) * 60 + (m || 0);
};
/** Local time (ms) at `date` + `hhmm`; DST-safe (built from local fields). */
export function localTime(date, hhmm) {
    const d = fromKey(date);
    const m = minutesOf(hhmm);
    d.setHours(Math.floor(m / 60), m % 60, 0, 0);
    return d.getTime();
}
/** When reminder `r` for an occurrence on `date` (start `time`, null = untimed) rings. */
export function fireTime(date, time, r) {
    if (r === 'morning')
        return localTime(date, MORNING);
    if (!time)
        return r === 1440 ? localTime(addDays(date, -1), MORNING) : localTime(date, MORNING);
    if (r === 1440)
        return localTime(addDays(date, -1), time);
    return localTime(date, time) - r * 60000;
}
const inWords = (mins) => (mins === 60 ? 'in 1 hour' : `in ${mins} min`);
/** Short and cute: "🦷 Dentist in 30 min", "🎂 Mom's birthday today ♡", "✅ Laundry tomorrow at 3:00 PM". */
export function reminderContent(item, r) {
    const head = `${item.emoji || (item.kind === 'event' ? '📅' : '🌸')} ${item.title}`.trim();
    const t = item.time;
    let title;
    if (r === 1440)
        title = t ? `${head} tomorrow at ${formatTime(t)}` : `${head} tomorrow`;
    else if (!t)
        title = `${head} today ♡`;
    else if (r === 'morning')
        title = `${head} today at ${formatTime(t)}`;
    else if (r === 0)
        title = item.kind === 'event' ? `${head} is starting ♡` : `${head} · it’s time ♡`;
    else
        title = `${head} ${inWords(r)}`;
    let body;
    if (item.kind === 'event') {
        const when = t ? formatTimeRange(t, item.end) : 'All day';
        body = item.location ? `${when} · ${item.location}` : when;
    }
    else
        body = r === 1440 ? 'On your list for tomorrow ♡' : 'On your list today ♡';
    return { title, body };
}
/**
 * Occurrence dates of `item` on/after `from`, soonest first, at most `max`, within `HORIZON_DAYS`
 * (a repeating item's next occurrence is always included even when it's further out, e.g. yearly).
 */
export function upcomingDates(item, from, max, horizon = HORIZON_DAYS) {
    const t = { dueDate: item.date, repeat: item.repeat, createdAt: item.createdAt };
    if (!item.repeat)
        return item.date && item.date >= from ? [item.date] : [];
    const out = [];
    const last = addDays(from, horizon);
    let d = occursOn(t, from) ? from : nextOccurrence(t, from);
    while (d && out.length < max && (d <= last || out.length === 0)) {
        out.push(d);
        d = nextOccurrence(t, d);
    }
    return out;
}
/**
 * Every reminder that should be pending at `now`, soonest first, capped at `cap` (iOS allows 64).
 * Repeating items contribute their next occurrences; `skip(itemId, date)` drops ticked / snoozed ones.
 * One-off reminders that already rang (fire time ≤ now) are left out.
 */
export function planReminders(items, opts) {
    const cap = opts.cap ?? PENDING_CAP;
    // a reminder can ring a day before its occurrence, so start looking from today
    const from = toKey(new Date(opts.now));
    const all = [];
    for (const item of items) {
        const rs = normalizeReminders(item.reminders);
        if (!rs.length || !item.title.trim())
            continue;
        const perItem = [];
        // enough occurrences to fill the cap on their own; the global sort keeps the soonest overall
        for (const date of upcomingDates(item, from, cap + 1)) {
            if (opts.skip?.(item, date))
                continue;
            for (const r of rs) {
                const fireAt = fireTime(date, item.time, r);
                if (fireAt <= opts.now)
                    continue;
                const { title, body } = reminderContent(item, r);
                perItem.push({ key: `${item.kind}:${item.id}@${date}#${r}`, itemId: item.id, kind: item.kind, date, fireAt, title, body, sig: `${fireAt}|${title}|${body}` });
            }
            if (perItem.length >= cap)
                break;
        }
        all.push(...perItem);
    }
    all.sort((a, b) => a.fireAt - b.fireAt || (a.key < b.key ? -1 : 1));
    return all.slice(0, cap);
}
/**
 * What to change so the pending notifications match `desired`:
 * - `cancel`: stored rows no longer wanted, changed (sig), or whose notification is gone from the OS (`pending`
 *   ids, when known) — they're cancelled (if still pending) and their rows deleted;
 * - `schedule`: wanted ones without a (valid) stored row;
 * - `orphans`: our pending notification ids with no stored row (e.g. after a restore) — cancel them.
 */
export function diffReminders(desired, stored, pending, ours) {
    const want = new Map(desired.map((d) => [d.key, d]));
    const keep = new Set();
    const cancel = [];
    for (const s of stored) {
        const d = want.get(s.key);
        const gone = !!pending && !pending.has(s.notifId);
        if (d && d.sig === s.sig && !gone)
            keep.add(s.key);
        else
            cancel.push(s);
    }
    const schedule = desired.filter((d) => !keep.has(d.key));
    const known = new Set(stored.map((s) => s.notifId));
    const orphans = (ours ?? []).filter((id) => !known.has(id));
    return { cancel, schedule, orphans };
}
