// GENERATED by tools/build.mjs from emm-blog-app/src/features/today/templates.ts. Do not edit.
export const TEMPLATES = [
    {
        kind: 'cleaning',
        name: 'Cleaning',
        emoji: null,
        mode: 'weekly',
        blurb: 'Weekly, a little each day, so nothing piles up',
        area: 'Home',
        days: {
            1: { label: 'Kitchen', chores: ['Wipe counters', 'Clean stovetop', 'Empty fridge leftovers'] },
            2: { label: 'Bathrooms', chores: ['Toilets', 'Sinks', 'Mirrors', 'Shower'] },
            3: { label: 'Dusting', chores: ['Surfaces', 'Shelves', 'TV area'] },
            4: { label: 'Floors', chores: ['Vacuum', 'Mop'] },
            5: { label: 'Laundry', chores: ['Wash', 'Fold', 'Put away'] },
            6: { label: 'Sheets & towels', chores: ['Change sheets', 'Wash towels'] },
            0: { label: 'Rest ♡', chores: ['Tidy for 10 min'] },
        },
    },
    {
        kind: 'morning',
        name: 'Morning routine',
        emoji: null,
        mode: 'daily',
        blurb: 'A soft start to the day',
        area: 'Self-care',
        chores: ['Drink a glass of water', 'Make the bed', 'Skincare', 'Take vitamins'],
    },
    {
        kind: 'evening',
        name: 'Evening routine',
        emoji: null,
        mode: 'daily',
        blurb: 'Wind down gently',
        area: 'Self-care',
        chores: ['Tidy up for 10 min', 'Skincare', 'Lay out tomorrow’s clothes', 'Phone away, read a little'],
    },
];
export const templateFor = (kind) => TEMPLATES.find((t) => t.kind === kind) ?? null;
/** The areas offered as chips (she can type her own too). */
export const AREAS = ['Home', 'Self-care', 'Errands', 'Work'];
