// GENERATED by tools/build.mjs from emm-blog-app/src/features/recipes/share/codec.ts. Do not edit.
// Recipe sharing between app users, with no cloud storage (see ARCHITECTURE.md › Recipes › Recipe sharing).
// PURE module (fflate only, no React Native imports) so it runs in node tests too.
//
// Link:  https://emm-blog-app.expo.app/r#1.<json>[.<photo>]
//   <json>  = base64url( deflate-raw( UTF-8 JSON of SharedRecipe ) )
//   <photo> = base64url( tiny JPEG thumbnail bytes )   (optional; kept out of the JSON so it isn't base64'd twice)
// The data lives in the URL FRAGMENT, which browsers never send to the server: nothing is stored or logged.
// The same "1.…" string is the `d` param of the in-app deep link emmblog://recipes/receive?d=…
//
// File:  <Title>.emmrecipe = a zip with recipe.json (the same SharedRecipe JSON, uncompressed text) + photo.jpg.
import { deflateSync, Inflate, strFromU8, strToU8 } from '../../../vendor/fflate.js';
export const SHARE_VERSION = 1;
export const SHARE_ORIGIN = 'https://emm-blog-app.expo.app';
export const SHARE_PAGE = `${SHARE_ORIGIN}/r`;
/** Whole https link must stay under this (Messages, WhatsApp, etc. all cope; the photo is dropped first). */
export const LINK_BUDGET = 8000;
// ---- limits for anything coming IN (links, files) ----
export const LIMITS = {
    /** decompressed JSON */
    jsonBytes: 200 * 1024,
    /** the "1.…" payload string (link / deep link) */
    payloadChars: 64 * 1024,
    /** photo in a link (bytes) */
    linkPhotoBytes: 48 * 1024,
    /** photo.jpg in a file (bytes) */
    filePhotoBytes: 15 * 1024 * 1024,
    /** whole .emmrecipe file */
    fileBytes: 16 * 1024 * 1024,
    /** max image side (px) */
    imageSide: 10000,
    items: 200,
    title: 200,
    emoji: 16,
    ingredient: 500,
    step: 2000,
    notes: 5000,
    tags: 20,
    tag: 40,
    url: 2000,
    from: 40,
};
export class ShareDecodeError extends Error {
    constructor(reason, message) {
        super(message ?? reason);
        this.reason = reason;
    }
}
// ---------------------------------------------------------------------------
// sanitizing (both directions: what we send and what we accept)
// ---------------------------------------------------------------------------
// C0/C1 controls except \n and \t, DEL, our list-item separator \u001F, bidi overrides/isolates, BOM
const CONTROL_RE = /[\u0000-\u0008\u000B-\u001F\u007F-\u009F‎‏‪-‮⁦-⁩﻿]/g;
/** Strip control chars, normalize newlines, trim, cap length. `multiline=false` collapses whitespace. */
export function cleanText(v, max, multiline = false) {
    if (typeof v !== 'string')
        return '';
    let s = v.replace(/\r\n?/g, '\n').replace(CONTROL_RE, '');
    s = multiline ? s.replace(/\t/g, ' ').replace(/\n{3,}/g, '\n\n') : s.replace(/\s+/g, ' ');
    s = s.trim();
    return s.length > max ? s.slice(0, max).trimEnd() : s;
}
function cleanInt(v, min, max) {
    if (typeof v !== 'number' || !Number.isFinite(v))
        return null;
    const n = Math.round(v);
    return n < min || n > max ? null : n;
}
function cleanList(v, maxItems, maxLen) {
    if (!Array.isArray(v))
        return [];
    const out = [];
    for (const x of v.slice(0, maxItems)) {
        const s = cleanText(x, maxLen, true);
        if (s)
            out.push(s);
    }
    return out;
}
export function cleanUrl(v) {
    if (typeof v !== 'string' || v.length > LIMITS.url)
        return undefined;
    const s = v.trim();
    if (!/^https?:\/\/[^\s<>"']+$/i.test(s))
        return undefined;
    try {
        const u = new URL(s);
        if ((u.protocol !== 'https:' && u.protocol !== 'http:') || u.username || u.password)
            return undefined;
        return s;
    }
    catch {
        return undefined;
    }
}
/** Validate + sanitize untrusted JSON into a SharedRecipe. Throws ShareDecodeError. */
export function sanitizeShared(raw) {
    if (!raw || typeof raw !== 'object' || Array.isArray(raw))
        throw new ShareDecodeError('not_recipe');
    const o = raw;
    if (typeof o.v === 'number' && o.v > SHARE_VERSION)
        throw new ShareDecodeError('newer');
    if (o.v !== SHARE_VERSION)
        throw new ShareDecodeError('not_recipe');
    const title = cleanText(o.title, LIMITS.title);
    const ingredients = cleanList(o.ingredients, LIMITS.items, LIMITS.ingredient);
    const steps = cleanList(o.steps, LIMITS.items, LIMITS.step);
    if (!title && !ingredients.length && !steps.length)
        throw new ShareDecodeError('not_recipe');
    const out = {
        v: 1,
        title: title || 'A shared recipe',
        emoji: cleanText(o.emoji, LIMITS.emoji) || '🍰',
        servings: cleanInt(o.servings, 1, 999),
        prepMin: cleanInt(o.prepMin, 0, 10000),
        cookMin: cleanInt(o.cookMin, 0, 10000),
        ingredients,
        steps,
        notes: cleanText(o.notes, LIMITS.notes, true),
        tags: [...new Set(cleanList(o.tags, LIMITS.tags, LIMITS.tag).map((t) => t.toLowerCase().replace(/\s+/g, ' ')))],
    };
    const sourceUrl = cleanUrl(o.sourceUrl);
    if (sourceUrl) {
        out.sourceUrl = sourceUrl;
        const st = cleanText(o.sourceTitle, LIMITS.title);
        if (st)
            out.sourceTitle = st;
    }
    const from = cleanText(o.from, LIMITS.from);
    if (from)
        out.from = from;
    return out;
}
// ---------------------------------------------------------------------------
// base64url (own implementation: same in Hermes and node, no atob/Buffer)
// ---------------------------------------------------------------------------
const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
const B64_INV = (() => {
    const t = new Int16Array(128).fill(-1);
    for (let i = 0; i < 64; i++)
        t[B64.charCodeAt(i)] = i;
    t['+'.charCodeAt(0)] = 62; // tolerate standard base64 too
    t['/'.charCodeAt(0)] = 63;
    return t;
})();
export function toBase64Url(bytes) {
    let out = '';
    let i = 0;
    for (; i + 2 < bytes.length; i += 3) {
        const n = (bytes[i] << 16) | (bytes[i + 1] << 8) | bytes[i + 2];
        out += B64[n >> 18] + B64[(n >> 12) & 63] + B64[(n >> 6) & 63] + B64[n & 63];
    }
    const rest = bytes.length - i;
    if (rest === 1) {
        const n = bytes[i] << 16;
        out += B64[n >> 18] + B64[(n >> 12) & 63];
    }
    else if (rest === 2) {
        const n = (bytes[i] << 16) | (bytes[i + 1] << 8);
        out += B64[n >> 18] + B64[(n >> 12) & 63] + B64[(n >> 6) & 63];
    }
    return out;
}
export function fromBase64Url(s) {
    const clean = s.replace(/=+$/, '');
    if (clean.length % 4 === 1)
        throw new ShareDecodeError('malformed');
    const out = new Uint8Array(Math.floor((clean.length * 3) / 4));
    let o = 0;
    let acc = 0;
    let bits = 0;
    for (let i = 0; i < clean.length; i++) {
        const code = clean.charCodeAt(i);
        const v = code < 128 ? B64_INV[code] : -1;
        if (v < 0)
            throw new ShareDecodeError('malformed');
        acc = (acc << 6) | v;
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            out[o++] = (acc >> bits) & 255;
        }
    }
    return out.subarray(0, o);
}
/** standard base64 (for data: URIs / expo-file-system) */
export const base64UrlToStd = (s) => {
    const t = s.replace(/-/g, '+').replace(/_/g, '/');
    return t + '='.repeat((4 - (t.length % 4)) % 4);
};
// ---------------------------------------------------------------------------
// deflate / bounded inflate
// ---------------------------------------------------------------------------
/** Inflate raw deflate data, refusing anything that grows past `max` bytes (zip bombs). */
export function inflateBounded(data, max) {
    const parts = [];
    let total = 0;
    let over = false;
    const inf = new Inflate((chunk) => {
        total += chunk.length;
        if (total > max)
            over = true;
        else
            parts.push(chunk.slice());
    });
    const STEP = 1024;
    try {
        for (let i = 0; i < data.length && !over; i += STEP)
            inf.push(data.subarray(i, i + STEP), i + STEP >= data.length);
        if (!data.length)
            inf.push(new Uint8Array(0), true);
    }
    catch {
        throw new ShareDecodeError('malformed');
    }
    if (over)
        throw new ShareDecodeError('too_big');
    const out = new Uint8Array(total);
    let o = 0;
    for (const p of parts) {
        out.set(p, o);
        o += p.length;
    }
    return out;
}
// ---------------------------------------------------------------------------
// JPEG sniffing (size check before anything decodes the image)
// ---------------------------------------------------------------------------
export const isJpeg = (b) => b.length > 4 && b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff;
/** Ends with the EOI marker (a link cut off mid-photo fails this). */
export const jpegComplete = (b) => b.length > 4 && b[b.length - 2] === 0xff && b[b.length - 1] === 0xd9;
/** Width/height from a JPEG's SOF marker (null when not found in the given bytes). */
export function jpegSize(b) {
    if (!isJpeg(b))
        return null;
    let p = 2;
    while (p + 9 < b.length) {
        if (b[p] !== 0xff) {
            p++;
            continue;
        }
        const m = b[p + 1];
        if (m === 0xff) {
            p++;
            continue;
        }
        if (m === 0xd8 || m === 0x01 || (m >= 0xd0 && m <= 0xd7)) {
            p += 2;
            continue;
        }
        const len = (b[p + 2] << 8) | b[p + 3];
        // SOF0..SOF15 except DHT(C4), JPG(C8), DAC(CC)
        if (m >= 0xc0 && m <= 0xcf && m !== 0xc4 && m !== 0xc8 && m !== 0xcc) {
            return { height: (b[p + 5] << 8) | b[p + 6], width: (b[p + 7] << 8) | b[p + 8] };
        }
        if (m === 0xda || len < 2)
            return null; // start of scan before SOF = odd file
        p += 2 + len;
    }
    return null;
}
export function checkPhoto(bytes, maxBytes) {
    if (!isJpeg(bytes) || !jpegComplete(bytes) || bytes.length > maxBytes)
        return false;
    const s = jpegSize(bytes);
    return !!s && s.width > 0 && s.height > 0 && s.width <= LIMITS.imageSide && s.height <= LIMITS.imageSide;
}
// ---------------------------------------------------------------------------
// link encode / decode
// ---------------------------------------------------------------------------
export function encodeJsonSegment(r) {
    return toBase64Url(deflateSync(strToU8(JSON.stringify(r)), { level: 9 }));
}
export function encodePayload(r, photo) {
    const json = encodeJsonSegment(r);
    return photo?.length ? `${SHARE_VERSION}.${json}.${toBase64Url(photo)}` : `${SHARE_VERSION}.${json}`;
}
export const linkFor = (payload) => `${SHARE_PAGE}#${payload}`;
/**
 * Build the share link within LINK_BUDGET: tries each photo candidate (biggest first) and keeps the first that
 * fits; drops the photo when none does. `photoDropped` = a photo was offered but didn't fit.
 */
export function buildShareLink(r, photos = [], budget = LINK_BUDGET) {
    const bare = encodePayload(r);
    const base = linkFor(bare).length;
    for (const p of photos) {
        if (!p.length)
            continue;
        const extra = 1 + Math.ceil((p.length * 4) / 3);
        if (base + extra <= budget) {
            const payload = encodePayload(r, p);
            return { url: linkFor(payload), payload, withPhoto: true, photoDropped: false };
        }
    }
    return { url: linkFor(bare), payload: bare, withPhoto: false, photoDropped: photos.some((p) => p.length > 0) };
}
/** Find the "1.…" payload in a deep-link param, a full https link, or a bare fragment. */
export function extractPayload(input) {
    const s = input.trim();
    const hash = s.indexOf('#');
    const cand = hash >= 0 ? s.slice(hash + 1) : s;
    let t = cand.trim();
    try {
        if (/%[0-9a-f]{2}/i.test(t))
            t = decodeURIComponent(t);
    }
    catch { }
    return /^\d+\.[A-Za-z0-9_-]+(\.[A-Za-z0-9_-]*)?$/.test(t) ? t : null;
}
/** The payload of the first share link (https …/r#…) in some pasted text, or null. */
export function shareLinkPayload(text) {
    const m = /https:\/\/emm-blog-app\.expo\.app\/r\/?#([A-Za-z0-9._%-]+)/i.exec(text);
    return m ? extractPayload(m[1]) : null;
}
/** Is there one of our share links in this text? */
export const isShareLink = (text) => shareLinkPayload(text) !== null;
/** Decode + validate a payload (never throws anything but ShareDecodeError). */
export function decodePayload(input) {
    if (!input || !input.trim())
        throw new ShareDecodeError('empty');
    if (input.length > LIMITS.payloadChars)
        throw new ShareDecodeError('too_big');
    const payload = extractPayload(input);
    if (!payload)
        throw new ShareDecodeError('malformed');
    const [ver, json, photo] = payload.split('.');
    const v = Number(ver);
    if (v > SHARE_VERSION)
        throw new ShareDecodeError('newer');
    if (v !== SHARE_VERSION || !json)
        throw new ShareDecodeError('malformed');
    let parsed;
    try {
        const bytes = inflateBounded(fromBase64Url(json), LIMITS.jsonBytes);
        parsed = JSON.parse(strFromU8(bytes));
    }
    catch (e) {
        if (e instanceof ShareDecodeError)
            throw e;
        throw new ShareDecodeError('malformed');
    }
    const recipe = sanitizeShared(parsed);
    let img = null;
    if (photo) {
        try {
            const b = fromBase64Url(photo);
            img = checkPhoto(b, LIMITS.linkPhotoBytes) ? b : null; // a bad photo never blocks the recipe
        }
        catch {
            img = null;
        }
    }
    return { recipe, photo: img };
}
/** recipe.json inside a .emmrecipe file */
export function decodeRecipeJson(bytes) {
    if (bytes.length > LIMITS.jsonBytes)
        throw new ShareDecodeError('too_big');
    let parsed;
    try {
        parsed = JSON.parse(strFromU8(bytes));
    }
    catch {
        throw new ShareDecodeError('malformed');
    }
    return sanitizeShared(parsed);
}
export function friendlyShareError(e) {
    const reason = e instanceof ShareDecodeError ? e.reason : 'malformed';
    switch (reason) {
        case 'empty':
            return { title: 'Nothing to open', message: 'That link didn’t have a recipe in it.' };
        case 'too_big':
            return { title: 'That one’s too big', message: 'This recipe is bigger than Em&m Blog can open. Ask them to send it again?' };
        case 'newer':
            return { title: 'Update the app first', message: 'This recipe was sent from a newer Em&m Blog. Update the app, then open it again ♡' };
        case 'backup':
            return { title: 'That’s a backup', message: 'This file is an Em&m Blog backup, not a recipe. To restore it, go to Me → Your data → Restore.' };
        case 'not_recipe':
            return { title: 'No recipe in there', message: 'That doesn’t look like an Em&m Blog recipe.' };
        default:
            return { title: 'That link looks broken', message: 'Part of the recipe is missing (links sometimes get cut off). Ask them to send it again ♡' };
    }
}
// ---------------------------------------------------------------------------
// misc helpers shared by send / receive
// ---------------------------------------------------------------------------
/** A safe file name for "<Title>.emmrecipe". */
export function recipeFileName(title) {
    const base = cleanText(title, 60)
        .replace(/[\\/:*?"<>|#%&{}$!'@`=+^~[\]]/g, '')
        .replace(/\s+/g, ' ')
        .trim()
        .replace(/^\.+/, '');
    return `${base || 'Recipe'}.emmrecipe`;
}
/** Same title + same ingredient lines = the same recipe (for "you already have this one"). */
export function recipeFingerprint(title, ingredients) {
    const norm = (s) => s.toLowerCase().replace(/\s+/g, ' ').trim();
    return `${norm(title)}\n${ingredients.map(norm).join('\n')}`;
}
