// GENERATED by tools/build.mjs from emm-blog-app/src/features/garden/copy.ts. Do not edit.
// Little bits of Habit Garden copy shared by the garden screen, Today and the widget snapshot. Pure.
import { REVIVE_AFTER, describeSchedule } from './growth.js';
export function streakText(p) {
    if (p.streak <= 0)
        return null;
    return p.streakUnit === 'week' ? `${p.streak}-week streak` : `${p.streak}-day streak`;
}
/** The one muted meta line under a habit: progress for weekly habits, the streak, or how the plant feels. */
export function habitMeta(p, schedule) {
    const parts = [];
    if (p.dried)
        parts.push(p.reviving ? `reviving · ${REVIVE_AFTER - p.reviving} more to go` : 'dried up · water it 3 days to revive');
    else if (p.mood === 'wilted')
        parts.push('wilting · needs you');
    else if (p.mood === 'thirsty')
        parts.push('a little thirsty');
    if (schedule.k === 'weekly')
        parts.push(`${p.weekDone} of ${p.weekNeed} this week`);
    else {
        const s = streakText(p);
        if (s)
            parts.push(s);
    }
    if (!parts.length)
        parts.push(describeSchedule(schedule));
    return parts.slice(0, 2).join(' · ');
}
/** "3 of 5 watered" / "All watered ♡" / "Nothing to water today". */
export function wateredLine(due, done) {
    if (!due)
        return 'Nothing to water today';
    if (done >= due)
        return 'All watered ♡';
    return `${done} of ${due} watered`;
}
