// GENERATED by tools/build.mjs from emm-blog-app/src/features/garden/growth.ts. Do not edit.
// ---------------------------------------------------------------------------
// Habit Garden: the pure plant model. NO React Native / expo imports (node-testable).
//
// Everything is computed from the check-in history + the schedule, day by day from the day the habit was
// planted up to today, so a backup/restore, a date change or an edit always gives the same garden. Nothing
// here uses timers or "now" except the `today` key the caller passes in.
//
// Rules (see ARCHITECTURE.md › Habit Garden):
// - A watered day (a `habit_checks` row) grows the plant one step and restores health (+0.35).
// - A due day that passed without watering is a miss: first miss → thirsty, 2–6 in a row → wilted, 7 → dried.
//   Days that aren't due never count. Today only counts once it's over.
// - Growth never goes down. A dried plant stays in the bed; 3 waterings in a row (no miss between) revive it
//   as a sprout (growth resets to sprout, `revived` counts up for the badge).
// - "N times a week" habits are judged per week (Mon–Sun): each missing watering is a miss when the week ends.
// ---------------------------------------------------------------------------
import { addDays, daysBetween, dow, weekStart } from '../today/recurrence.js';
export const SPECIES = ['tulip', 'daisy', 'sunflower', 'rose', 'lavender', 'strawberry', 'cherry', 'cactus'];
/** Everyone starts with these three; the rest are earned (rewards.ts). */
export const STARTER_SPECIES = ['tulip', 'daisy', 'sunflower'];
export const SPECIES_INFO = {
    tulip: { name: 'Tulip', emoji: '🌷' },
    daisy: { name: 'Daisy', emoji: '🌼' },
    sunflower: { name: 'Sunflower', emoji: '🌻' },
    rose: { name: 'Rose', emoji: '🌹' },
    lavender: { name: 'Lavender', emoji: '💜' },
    strawberry: { name: 'Strawberry', emoji: '🍓' },
    cherry: { name: 'Cherry blossom', emoji: '🌸' },
    cactus: { name: 'Cactus', emoji: '🌵' },
};
export const isSpecies = (s) => typeof s === 'string' && SPECIES.includes(s);
export const STAGES = ['seed', 'sprout', 'leaves', 'bud', 'bloom', 'full'];
/** Waterings needed to reach each stage (growth points). */
export const STAGE_AT = { seed: 0, sprout: 1, leaves: 4, bud: 8, bloom: 12, full: 21 };
export const FULL_POINTS = STAGE_AT.full;
// ---------- tuning (gentle on purpose) ----------
export const START_HEALTH = 0.9;
export const WATER_HEALTH = 0.35;
export const MISS_STEP = 0.15;
/** health ceiling after the Nth miss in a row */
export const MISS_CURVE = [1, 0.6, 0.4, 0.3, 0.22, 0.15, 0.08, 0];
export const DRY_AFTER = 7;
export const REVIVE_AFTER = 3;
export const REVIVE_HEALTH = 0.7;
export function moodOf(health, dried) {
    if (dried)
        return 'dried';
    if (health >= 0.85)
        return 'thriving';
    if (health >= 0.62)
        return 'ok';
    if (health >= 0.45)
        return 'thirsty';
    return 'wilted';
}
export function stageOf(points) {
    let s = 'seed';
    for (const st of STAGES)
        if (points >= STAGE_AT[st])
            s = st;
    return s;
}
export function weatherOf(avgHealth, plants = 1) {
    if (plants === 0 || avgHealth >= 0.85)
        return 'sunny';
    if (avgHealth >= 0.65)
        return 'partly';
    if (avgHealth >= 0.45)
        return 'cloudy';
    return 'rain';
}
export const WEATHER_LABEL = { sunny: 'sunny ✨', partly: 'partly cloudy ⛅', cloudy: 'cloudy ☁️', rain: 'rainy 🌧️' };
export const MOOD_LABEL = { thriving: 'thriving ✨', ok: 'doing okay', thirsty: 'a little thirsty 💧', wilted: 'wilting 🥺', dried: 'dried up' };
export const STAGE_LABEL = { seed: 'Seed', sprout: 'Sprout', leaves: 'Leafy', bud: 'Budding', bloom: 'Blooming', full: 'Full bloom' };
// ---------- schedules ----------
export function cleanSchedule(s) {
    const o = (s ?? {});
    if (o.k === 'days' && Array.isArray(o.days)) {
        const days = [...new Set(o.days.map(Number).filter((d) => Number.isInteger(d) && d >= 0 && d <= 6))].sort();
        if (days.length === 7)
            return { k: 'daily' };
        if (days.length)
            return { k: 'days', days };
    }
    if (o.k === 'weekly') {
        const times = Math.round(Number(o.times));
        if (times >= 7)
            return { k: 'daily' };
        if (times >= 1)
            return { k: 'weekly', times };
    }
    return { k: 'daily' };
}
/** daily / days: is `day` a due day? (weekly habits have no fixed days: always false) */
export function isDueDay(s, day) {
    if (s.k === 'daily')
        return true;
    if (s.k === 'days')
        return s.days.includes(dow(day));
    return false;
}
const DAY_ABBR = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
export function describeSchedule(s) {
    if (s.k === 'daily')
        return 'Every day';
    if (s.k === 'weekly')
        return s.times === 1 ? 'Once a week' : `${s.times}× a week`;
    const d = [...s.days].sort();
    if (d.join() === '1,2,3,4,5')
        return 'Weekdays';
    if (d.join() === '0,6')
        return 'Weekends';
    // Mon first
    return [...d].sort((a, b) => ((a + 6) % 7) - ((b + 6) % 7)).map((x) => DAY_ABBR[x]).join(' · ');
}
/** Waterings needed in the week starting `monday` (the first, partial week asks for proportionally fewer). */
function weekNeed(times, monday, start) {
    if (start <= monday)
        return times;
    const active = 7 - daysBetween(monday, start);
    return Math.max(0, Math.floor((times * active) / 7));
}
// ---------- the simulation ----------
const asSet = (c) => (c instanceof Set ? c : new Set(c));
/** First day the model looks at: the planting day (or an earlier watering, e.g. imported/back-dated). */
export function startDay(h) {
    let s = h.createdDay;
    for (const d of asSet(h.checks))
        if (d < s)
            s = d;
    return s;
}
/** Replay a habit's whole history up to (and including) `today`. */
export function simulate(h, today) {
    const checks = asSet(h.checks);
    const sched = h.schedule;
    const weekly = sched.k === 'weekly';
    const start = startDay(h);
    let points = 0;
    let maxPoints = 0;
    let health = START_HEALTH;
    let misses = 0;
    let dried = false;
    let reviving = 0;
    let revived = 0;
    let streak = 0; // days (daily/days) or closed weeks (weekly)
    let best = 0;
    let waters = 0;
    let weekGot = 0;
    const water = (dueDay) => {
        waters++;
        if (dried) {
            reviving++;
            if (reviving >= REVIVE_AFTER) {
                dried = false;
                reviving = 0;
                revived++;
                points = STAGE_AT.sprout;
                health = REVIVE_HEALTH;
                misses = 0;
            }
        }
        else {
            points++;
            maxPoints = Math.max(maxPoints, points);
            health = Math.min(1, health + WATER_HEALTH);
            misses = 0;
        }
        if (dueDay) {
            streak++;
            best = Math.max(best, streak);
        }
    };
    const miss = () => {
        if (!weekly)
            streak = 0;
        if (dried) {
            reviving = 0;
            return;
        }
        misses++;
        health = Math.max(0, Math.min(health - MISS_STEP, MISS_CURVE[Math.min(misses, MISS_CURVE.length - 1)]));
        if (misses >= DRY_AFTER) {
            dried = true;
            health = 0;
            reviving = 0;
        }
    };
    if (start <= today) {
        for (let d = start; d <= today; d = addDays(d, 1)) {
            const wet = checks.has(d);
            if (weekly) {
                if (dow(d) === 1)
                    weekGot = 0; // Monday: a new week
                if (wet) {
                    water(false);
                    weekGot++;
                }
                // Sunday closes the week (only once it's over)
                if (dow(d) === 0 && d < today) {
                    const need = weekNeed(sched.times, weekStart(d), start);
                    for (let i = weekGot; i < need; i++)
                        miss();
                    if (need > 0) {
                        if (weekGot >= need) {
                            streak++;
                            best = Math.max(best, streak);
                        }
                        else
                            streak = 0;
                    }
                }
            }
            else {
                const due = isDueDay(sched, d);
                if (wet)
                    water(due);
                else if (due && d < today)
                    miss();
            }
        }
    }
    const doneToday = checks.has(today);
    let dueToday = false;
    let weekDone = 0;
    let need = 0;
    let shownStreak = streak;
    if (weekly) {
        const monday = weekStart(today);
        need = today < start ? 0 : weekNeed(sched.times, monday, start);
        for (let d = monday; d <= today; d = addDays(d, 1))
            if (checks.has(d))
                weekDone++;
        dueToday = doneToday || weekDone < need;
        // this week counts toward the streak as soon as it's met
        if (need > 0 && weekDone >= need) {
            shownStreak = streak + 1;
            best = Math.max(best, shownStreak);
        }
    }
    else {
        dueToday = today >= start && isDueDay(sched, today);
    }
    return {
        id: h.id,
        growth: Math.min(1, points / FULL_POINTS),
        points,
        maxPoints,
        stage: stageOf(points),
        maxStage: stageOf(maxPoints),
        health,
        mood: moodOf(health, dried),
        dried,
        reviving,
        revived,
        misses,
        streak: shownStreak,
        bestStreak: best,
        streakUnit: weekly ? 'week' : 'day',
        dueToday,
        doneToday,
        weekDone,
        weekNeed: need,
        waters,
    };
}
/** The last `n` days for the plant sheet (oldest first). Weekly habits never show a single day as missed. */
export function dotHistory(h, today, n = 30) {
    const checks = asSet(h.checks);
    const start = startDay(h);
    const out = [];
    for (let i = n - 1; i >= 0; i--) {
        const date = addDays(today, -i);
        let dot;
        if (date < start)
            dot = 'none';
        else if (checks.has(date))
            dot = 'done';
        else if (h.schedule.k === 'weekly')
            dot = date === today ? 'today' : 'rest';
        else if (!isDueDay(h.schedule, date))
            dot = 'rest';
        else
            dot = date === today ? 'today' : 'missed';
        out.push({ date, dot });
    }
    return out;
}
// ---------- the whole garden ----------
/**
 * Garden streak: days in a row on which every due habit (daily / specific weekdays) was watered. Days with nothing
 * due don't break or extend it; today only counts once everything due today is done (it never breaks it).
 * "N times a week" habits aren't part of it (they have no due days).
 */
export function gardenStreak(habits, today) {
    const daily = habits.filter((h) => h.schedule.k !== 'weekly').map((h) => ({ h, start: startDay(h), checks: asSet(h.checks) }));
    if (!daily.length)
        return { current: 0, best: 0 };
    let from = today;
    for (const x of daily)
        if (x.start < from)
            from = x.start;
    let cur = 0;
    let best = 0;
    for (let d = from; d <= today; d = addDays(d, 1)) {
        const due = daily.filter((x) => x.start <= d && isDueDay(x.h.schedule, d));
        if (!due.length)
            continue;
        const all = due.every((x) => x.checks.has(d));
        if (all) {
            cur++;
            best = Math.max(best, cur);
        }
        else if (d < today)
            cur = 0;
    }
    return { current: cur, best };
}
export function summarize(habits, today) {
    const plants = habits.map((h) => simulate(h, today));
    const health = plants.length ? plants.reduce((a, p) => a + p.health, 0) / plants.length : 1;
    const g = gardenStreak(habits, today);
    const due = plants.filter((p) => p.dueToday);
    return {
        plants,
        weather: weatherOf(health, plants.length),
        health,
        due: due.length,
        done: due.filter((p) => p.doneToday).length,
        streak: g.current,
        bestStreak: g.best,
        waters: plants.reduce((a, p) => a + p.waters, 0),
    };
}
export function plantLook(p) {
    if (p.mood === 'dried')
        return 'dried';
    if (p.mood === 'wilted')
        return 'wilted';
    return p.stage;
}
