// GENERATED by tools/build.mjs from emm-blog-app/src/features/garden/rewards.ts. Do not edit.
// ---------------------------------------------------------------------------
// Habit Garden: decorations + flower species earned at milestones. Pure (node-testable).
// `earnedRewards` is deterministic from the garden; the repo stores each key in `garden_unlocks` the first time it's
// earned, so a reward never goes away again (even if the habit that earned it is archived or deleted).
// ---------------------------------------------------------------------------
import { STAGE_AT, STARTER_SPECIES } from './growth.js';
export const DECOS = ['watering-can', 'fence', 'stepping-stones', 'butterfly', 'bunny', 'bee', 'mushroom', 'birdhouse', 'fairy-lights', 'gnome'];
export const DECO_INFO = {
    'watering-can': { name: 'Watering can', emoji: '🪣' },
    fence: { name: 'Little fence', emoji: '🪵' },
    'stepping-stones': { name: 'Stepping stones', emoji: '🪨' },
    butterfly: { name: 'Butterfly', emoji: '🦋' },
    bunny: { name: 'Bunny', emoji: '🐰' },
    bee: { name: 'Bumble bee', emoji: '🐝' },
    mushroom: { name: 'Mushroom', emoji: '🍄' },
    birdhouse: { name: 'Birdhouse', emoji: '🏡' },
    'fairy-lights': { name: 'Fairy lights', emoji: '✨' },
    gnome: { name: 'Garden gnome', emoji: '🧙' },
};
/** In the order they're usually earned. Keys are stored in `garden_unlocks`: never rename one. */
export const REWARDS = [
    { key: 'first_water', hint: 'Water a plant for the first time', toast: 'A watering can for your garden', deco: 'watering-can' },
    { key: 'plants_3', hint: 'Plant 3 habits', toast: 'A little fence for your garden', deco: 'fence' },
    { key: 'streak_3', hint: 'Water everything 3 days in a row', toast: 'Stepping stones for your garden', deco: 'stepping-stones' },
    { key: 'first_bloom', hint: 'Grow your first bloom', toast: 'A butterfly came to visit — and roses unlocked', deco: 'butterfly', species: 'rose' },
    { key: 'streak_7', hint: 'A 7-day garden streak', toast: 'A bunny moved in — and lavender unlocked', deco: 'bunny', species: 'lavender' },
    { key: 'full_bloom', hint: 'Grow a plant to full bloom', toast: 'A bumble bee arrived — and strawberries unlocked', deco: 'bee', species: 'strawberry' },
    { key: 'revive', hint: 'Bring a dried plant back to life', toast: 'A mushroom popped up — and cactus unlocked', deco: 'mushroom', species: 'cactus' },
    { key: 'kept_5', hint: 'Keep 5 habits for a week each', toast: 'A birdhouse for your garden', deco: 'birdhouse' },
    { key: 'streak_30', hint: 'A 30-day garden streak', toast: 'Fairy lights — and cherry blossoms unlocked', deco: 'fairy-lights', species: 'cherry' },
    { key: 'streak_100', hint: 'A 100-day garden streak', toast: 'A garden gnome moved in', deco: 'gnome' },
];
export const rewardOf = (key) => REWARDS.find((r) => r.key === key);
/** Every reward the garden has earned by now (keys). */
export function earnedRewards(g) {
    const waters = g.plants.reduce((a, p) => a + p.waters, 0);
    const maxPoints = g.plants.reduce((a, p) => Math.max(a, p.maxPoints), 0);
    const revives = g.plants.reduce((a, p) => a + p.revived, 0) + (g.storedRevives ?? 0);
    const keptWeek = g.plants.filter((p) => (p.streakUnit === 'week' ? p.bestStreak >= 1 : p.bestStreak >= 7)).length;
    const out = [];
    const add = (key, ok) => ok && out.push(key);
    add('first_water', waters > 0);
    add('plants_3', g.planted >= 3);
    add('streak_3', g.bestGardenStreak >= 3);
    add('first_bloom', maxPoints >= STAGE_AT.bloom);
    add('streak_7', g.bestGardenStreak >= 7);
    add('full_bloom', maxPoints >= STAGE_AT.full);
    add('revive', revives > 0);
    add('kept_5', keptWeek >= 5);
    add('streak_30', g.bestGardenStreak >= 30);
    add('streak_100', g.bestGardenStreak >= 100);
    return out;
}
export function unlockedSpecies(keys) {
    const out = [...STARTER_SPECIES];
    for (const k of keys) {
        const s = rewardOf(k)?.species;
        if (s && !out.includes(s))
            out.push(s);
    }
    return out;
}
export function unlockedDecos(keys) {
    const set = new Set(keys);
    return REWARDS.filter((r) => r.deco && set.has(r.key)).map((r) => r.deco);
}
/** The reward that unlocks a species (for "earn it by…" hints), undefined for starters. */
export const speciesReward = (s) => REWARDS.find((r) => r.species === s);
